// W8-MUSE · MU-03 · Catálogo de microcopy pt-BR.
// Verbos claros, sem jargão de TI. Nenhum número de corte clínico aqui:
// limiares vivem em corpus/rulesets/*.json com fonte (o teste garante).
// Textos do kit do médico NÃO estão aqui (fonte DECISAO_MEDICA, intocados).

export const COPY_PT_BR = {
  app: {
    nome: "OncoMed",
    buscar: "Buscar paciente, exame, CID…",
    novoRegistro: "Novo registro",
    acoesRapidas: "Ações rápidas",
    verTodos: "Ver todos",
    verTodas: "Ver todas",
    fechar: "Fechar",
    voltar: "Voltar",
    cancelar: "Cancelar",
    confirmar: "Confirmar",
    salvarRascunho: "Salvar rascunho",
    rascunhoSalvo: "Rascunho salvo",
    imprimir: "Imprimir",
    imprimirBloco: "Imprimir selecionados",
    validarBloco: "Validar este bloco",
    validarTudo: "Validar tudo",
    assinar: "Assinar",
    configuracoes: "Configurações",
    diaNoite: "Dia / noite",
    buscarOncoChart: "Buscar pacientes, exames, protocolos…",
    alertasClinicos: "Alertas clínicos",
    modoDia: "Modo dia",
    modoNoite: "Modo noite",
    usuario: "Usuário",
  },
  navegacao: {
    salao: "Salão",
    canal: "Canal",
    consulta: "Consulta",
    resumo: "Resumo",
    prontuario: "Prontuário",
    exames: "Exames",
    prescricao: "Prescrição",
    apac: "APAC",
    documentos: "Documentos",
    agenda: "Agenda",
    enfermagem: "Enfermagem",
    farmacia: "Farmácia",
    relatorios: "Relatórios",
    configuracoes: "Configurações",
    medicoLogado: "Médico responsável",
  },
  semaforo: {
    verde: "Verde",
    vermelho: "Vermelho",
    pendente: "Pendente",
    pendencias: "pendências",
    verTodasPendencias: "Ver todas as pendências",
    alertasEPendencias: "Alertas e pendências",
    semAlerta: "Sem alerta com os dados disponíveis",
  },
  revisao: {
    recebido: "Recebido",
    sugestaoIA: "Sugestão da IA",
    sugestaoIASemLaudo: "Sugestão da IA — sem laudo",
    revisar: "Revisar",
    confirmadoPor: "Confirmado por",
    assinadoPor: "Assinado por",
    rascunho: "Rascunho",
    naoValido: "RASCUNHO — NÃO VÁLIDO",
    escopoAssinatura: "A assinatura cobre só o que foi exibido",
  },
  conflito: {
    titulo: "Conflito",
    candidatos: "Candidatos",
    escolher: "Escolher este",
    escolhido: "Escolhido pelo médico",
    naoEscolhido: "Não escolhido",
    rotuloContraValor: "Rótulo × valor",
    ajuda: "Os candidatos coexistem até você escolher. Nada é ligado em silêncio.",
  },
  campo: {
    ausente: "Ausente",
    naoDescrito: "Não descrito",
    naoSeAplica: "Não se aplica",
    pendente: "Pendente",
    conferirRecorte: "Conferir no recorte",
    trechoRiscado: "Trecho riscado à mão: não usar sem revisão",
    baixaConfianca: "Leitura incerta: confira no original",
    mencionadoSemLaudo: "Mencionado sem laudo",
  },
  consulta: {
    evolucao: "Evolução",
    prescricao: "Prescrição",
    exames: "Exames",
    dadosAnagraficos: "Dados anagráficos",
    dadosClinicosGerais: "Dados clínicos gerais",
    antecedentes: "Antecedentes",
    medicacoes: "Medicações",
    alergias: "Alergias",
    alergiaNaoRevisada: "Alergia não revisada",
    cirurgiasPrevias: "Cirurgias prévias",
    exameFisico: "Exame físico",
    ecog: "ECOG",
    ecogAjuda: "Escolher o ECOG monta o rascunho do texto, nunca o fato",
    evolucoesRecentes: "Evoluções recentes",
    condutaAtual: "Conduta atual",
    linhaDoTempo: "Linha do tempo",
    verTodosEventos: "Ver todos os eventos",
    desdeUltimaConsulta: "Desde a última consulta",
    resumoDoCaso: "Resumo do caso",
    sugestaoPendencias: "Sugestão de pendências",
    rascunhoConduta: "Rascunho de conduta",
    comoPossoAjudar: "Como posso ajudar neste caso?",
    atualizacoesEDiretrizes: "Atualizações e diretrizes",
    verDetalhes: "Ver detalhes",
    verTodosOsDados: "Ver todos os dados",
    flash: "Consulta Flash",
    alergiaPendente: "Alergia PENDENTE",
    negaAlergias: "Nega alergias",
  },
  exame: {
    resumo1: "Resumo",
    resumo2: "Resumo detalhado",
    verResumo2: "Ver resumo detalhado",
    imagem: "Imagem",
    patologia: "Patologia",
    laboratorio: "Laboratório",
    coletadoEm: "Coletado em",
    anexos: "Anexos",
    anterior: "Anterior",
    proximo: "Próxima",
    telaCheia: "Tela cheia",
    ampliar: "Ampliar",
    reduzir: "Reduzir",
    labsRecentes: "Exames de laboratório recentes",
    verTodosLabs: "Ver todos os exames laboratoriais",
    hemograma: "Hemograma",
    funcaoRenal: "Função renal",
    funcaoHepatica: "Função hepática",
    outros: "Outros",
  },
  salao: {
    frente: "Frente",
    filaDoMedico: "Fila do médico",
    salao: "Salão",
    emergencia: "Emergência",
    escalonar: "Escalonar",
    triagem: "Triagem",
    resultadoTriagem: "Resultado da triagem",
    corte: "Corte",
    semCorte: "Sem corte",
    aguardandoTriagem: "Aguardando triagem",
    chamar: "Chamar",
    finalizar: "Finalizar atendimento",
  },
  agenda: {
    titulo: "Agenda",
    hoje: "Hoje",
    pendenciasDoDia: "Pendências do dia",
    confirmarPresenca: "Confirmar presença",
    remarcar: "Remarcar",
    faltou: "Faltou",
  },
  apac: {
    loteDoDia: "Lote do dia",
    competencia: "Competência",
    novaApac: "Nova APAC",
    renovar: "Renovar",
    emitir: "Emitir",
    emitida: "Emitida",
    autorizada: "Autorizada",
    negada: "Negada",
    vencida: "Vencida",
    validadeAte: "Válida até",
    avisoVencimento: "Vence em breve: providenciar renovação",
    foraDoLote: "Fora do lote",
    motivoForaDoLote: "Competência de outro mês: vai para o lote dele",
    solicitacao: "Solicitação",
    autorizacao: "Autorização",
    autorizacaoEmBranco: "Preenchido pelo autorizador",
    finalidade: "Finalidade",
    verLaudo: "Ver laudo",
  },
  documentos: {
    selecionarParaImprimir: "Marcar para imprimir",
    desmarcar: "Desmarcar",
    modeloEmBranco: "Imprimir modelo em branco",
    assinado: "Assinado",
    aguardandoAssinatura: "Aguardando assinatura",
  },
  farmacia: {
    enviada: "Enviada",
    conferida: "Conferida",
    correcaoPedida: "Correção pedida",
    aceita: "Aceita",
    aceitar: "Aceitar correção",
    recusar: "Recusar correção",
    correcaoDetalhe: "A farmácia pediu correção no chat",
  },
  estoque: {
    disponivel: "Disponível",
    indisponivel: "Indisponível",
  },
  canal: {
    conversaNova: "Nova conversa",
    aguardandoMedico: "Aguardando o médico",
    respondida: "Respondida",
    encerrada: "Encerrada",
    vincularContato: "Vincular contato",
    contatoDesconhecido: "Contato desconhecido",
    filaDeVinculo: "Fila de vínculo",
    respostaEmergencia: "Procure a emergência",
    escreverMensagem: "Escrever mensagem",
    enviar: "Enviar",
  },
  oncoassist: {
    titulo: "OncoAssist (IA)",
    desligado: "Capacidade não habilitada",
    desligadoAjuda: "Os botões existem, mas não chamam nada nesta versão",
    interromper: "Interromper",
    ouvirNovamente: "Ouvir novamente",
  },
  centroComando: {
    titulo: "Centro de comando",
    modulos: "Módulos",
    skills: "skills",
    versaoPrompt: "Versão do prompt",
    ativar: "Ativar",
    desativar: "Desativar",
    logAlteracoes: "Registro de alterações",
    desligarIA: "Desligar toda a IA por 30 min",
    desligarIAConfirmacao: "Desligar toda a IA agora e operar manual por 30 min?",
    iaDesligada: "IA desligada — operação manual",
    iaVoltaEm: "A IA volta sozinha em",
    breakGlassNota:
      "Nenhuma trava de segurança é liberada. Portas, assinaturas e envios continuam exigindo o médico.",
    quemQuandoMotivo: "Quem, quando e por quê",
  },
  abas: {
    visaoGeral: "Visão geral",
    quimioterapia: "Quimioterapia",
    dadosClinicos: "Dados clínicos",
    evolucao: "Evolução",
  },
  cards: {
    protocolos: "Protocolos ativos",
    documentos: "Documentos recentes",
    estadiamento: "Estadiamento e avaliações",
    rascunho: "Rascunho de evolução",
    caixaUnica: "Soltar PDF/Word — caixa única",
  },
  timeline: {
    titulo: "Linha do tempo oncológica",
    ver3d: "Ver em 3D",
  },
  cadastro: {
    titulo: "Cartão de cadastro",
  },
  vazios: {
    filaVazia: "Ninguém na fila",
    filaVaziaAjuda: "Novos pacientes aparecem aqui após a triagem",
    semExames: "Nenhum exame registrado",
    semExamesAjuda: "Exames vinculados ao paciente aparecem aqui",
    semMensagens: "Nenhuma mensagem",
    semMensagensAjuda: "Mensagens do canal do paciente chegam aqui",
    semPendencias: "Nenhuma pendência",
    semResultados: "Nada encontrado",
    semResultadosAjuda: "Confira a escrita ou busque por outro termo",
    semDocumentos: "Nenhum documento",
    loteVazio: "Nenhuma APAC no lote de hoje",
  },
  erros: {
    comandoIncompleto: "Comando incompleto: diga o nome do paciente e a ação",
    naoEntendi: "Não entendi. Repita com outras palavras",
    sessaoExpirada: "Sessão encerrada: entre de novo para continuar",
    impressaoFalhou: "Não foi possível abrir a impressão. Tente de novo",
    anexoGrande: "Arquivo grande demais para anexar",
    formatoNaoSuportado: "Formato não suportado",
    tenteNovamente: "Tente de novo",
    semConexaoLocal: "Serviço local indisponível no momento",
  },
  confirmacoes: {
    validarTudoTitulo: "Validar e assinar o selecionado?",
    validarTudoCorpo:
      "Confirma e assina só os documentos exibidos, nas versões mostradas. Nada fora da tela é assinado.",
    descartarRascunho: "Descartar este rascunho?",
    descartarRascunhoCorpo: "O rascunho sai da tela, mas fica guardado no registro.",
    imprimirTitulo: "Imprimir agora?",
    imprimirCorpo: "A impressão abre na janela do sistema, onde você escolhe a impressora.",
    sairSemSalvar: "Sair sem salvar?",
    sairSemSalvarCorpo: "O rascunho salvo continua guardado.",
  },
  avisosLegais: {
    iaNaoSubstitui: "As respostas da IA não substituem o julgamento clínico",
    cabecalhoExemplo: "Cabeçalho de exemplo: altere nas configurações",
    capacidadeNaoHabilitada: "Capacidade não habilitada",
    rascunhoNaoValido: "RASCUNHO — NÃO VÁLIDO",
    consentimentoCanal:
      "Mensagens do canal ficam guardadas só neste computador, com consentimento registrado",
    semDadosNaUrl: "Links de diretriz abrem sem nenhum dado do paciente",
  },
  transversal: {
    titulo: "Retrato transversal do tumor-índice",
    destaque: "Destaque: metástase e estádio",
    gradeTitulo: "Campos anatomopatológicos",
    extensaoTitulo: "Extensão do tumor",
    colunaCampo: "Campo",
    colunaValor: "Valor e origem",
    naoInformado: "não informado",
    naoSeAplica: "não se aplica",
    dataDesconhecida: "data desconhecida",
    laudo: "laudo",
    encaminhador: "afirmado pelo encaminhador (não confirmado)",
    baixaConfianca: "manuscrito/baixa confiança",
    conflito: "CONFLITO: nenhuma fonte foi escolhida",
    erroDados: "Erro de dados: o retrato anatomopatológico não pôde ser exibido. Nenhum valor parcial é mostrado.",
    erroCampos: "Campos com problema",
    sim: "sim",
    nao: "não",
    presente: "presente",
    ausente: "ausente",
  },
  acessibilidade: {
    pularParaConteudo: "Pular para o conteúdo",
    abrirMenu: "Abrir menu",
    fecharDialogo: "Fechar diálogo",
    paginaAnteriorCarrossel: "Imagem anterior",
    proximaPaginaCarrossel: "Próxima imagem",
    expandirSecao: "Expandir seção",
    recolherSecao: "Recolher seção",
  },
} as const;

export type CopyPtBr = typeof COPY_PT_BR;
