# -*- coding: utf-8 -*-
"""Minutas para adulto não gestante. Porta APS só quando a receita pode ser impressa na UBS."""

def C(id, especialidade, nome, cid, sinonimos, sintomas, diagnostico, foco, alarmes, nao_fazer, fontes, confianca, receitas):
    return dict(id=id, especialidade=especialidade, nome=nome, cid=cid, sinonimos=sinonimos,
                sintomas=sintomas, diagnostico=diagnostico, foco=foco, alarmes=alarmes,
                nao_fazer=nao_fazer, fontes=fontes, confianca=confianca, receitas=receitas)

def R(id, porta, imprimivel, cenario, linhas, duracao, quantidade, ajustes, alternativa, farmacos, confianca):
    return dict(id=id, porta=porta, imprimivel=imprimivel, cenario=cenario, linhas=linhas,
                duracao=duracao, quantidade=quantidade, ajustes=ajustes, alternativa=alternativa,
                farmacos=farmacos, confianca=confianca)

CONDICOES = []

CONDICOES.append(C(
    "has", "cardiologia", "Hipertensão arterial", "I10",
    ["HAS", "pressão alta", "hipertensão"],
    ["Em geral sem sintoma", "Cefaleia occipital, zumbido ou epistaxe não confirmam o diagnóstico"],
    "PA de consultório ≥ 140/90 mmHg em pelo menos duas ocasiões, com técnica correta. Meta da Diretriz Brasileira de Hipertensão Arterial 2025: abaixo de 130/80 mmHg se tolerada. Medidas não medicamentosas para todo mundo com PA ≥ 120/80. Medicamento imediato se ≥ 140/90. Se 130–139/80–89 e alto risco cardiovascular, medidas por 3 meses e então fármaco se não controlar.",
    "Classe preferencial: IECA ou BRA, com bloqueador de canal de cálcio ou tiazídico. A maioria começa com dois fármacos em dose baixa. Monoterapia cabe no risco mais baixo, no frágil, em quem tem 80 anos ou mais e na hipotensão ortostática.",
    ["PA ≥ 180/120 com lesão de órgão alvo: emergência, não é receita de UBS", "Dor torácica, falta de ar, déficit neurológico, gestação"],
    ["Não associar IECA com BRA", "Não usar atenolol como primeira classe sem indicação específica", "Não tratar edema do anlodipino com furosemida"],
    ["Diretriz Brasileira de Hipertensão Arterial 2025. DOI 10.36660/abc.20250624", "Rename 2024: losartana 50 mg, anlodipino 5 e 10 mg, hidroclorotiazida 12,5 e 25 mg, atenolol, captopril"],
    "alta",
    [
        R("has.associacao", "APS", True, "Adulto com HAS estágio 1 ou mais, sem fragilidade, sem ICFEr descompensada, não gestante.",
          ["Losartana potássica 50 mg: 1 comprimido pela manhã.",
           "Besilato de anlodipino 5 mg: 1 comprimido pela manhã.",
           "Medir a pressão em casa. Retorno em 4 semanas com o diário.",
           "Se a pressão seguir acima da meta, trocar o anlodipino para 10 mg ou acrescentar hidroclorotiazida 12,5 mg pela manhã, não as duas coisas no mesmo dia sem reavaliar."],
          "Uso contínuo", "30 comprimidos de cada, para 30 dias",
          "Dosar creatinina e potássio antes e em 2 a 4 semanas. Não usar se potássio alto ou estenose bilateral de artéria renal.",
          "Se tosse ou angioedema com IECA no passado, manter a losartana. Se não tolerar BRA, maleato de enalapril 10 mg pela manhã no lugar da losartana, nunca junto.",
          ["losartana", "anlodipino"], "alta"),
        R("has.mono", "APS", True, "PA 130–139/80–89 de alto risco após 3 meses de medidas, ou estágio 1 de baixo risco, ou frágil, ou 80 anos ou mais.",
          ["Losartana potássica 50 mg: 1 comprimido pela manhã.",
           "Retorno em 4 semanas. Só então associar o segundo fármaco se a meta não vier."],
          "Uso contínuo", "30 comprimidos",
          "Mesma checagem de creatinina e potássio.",
          "Hidroclorotiazida 12,5 mg pela manhã se o BRA for contraindicado e não houver gota, hiponatremia ou TFG muito baixa.",
          ["losartana"], "alta"),
        R("has.quarta", "APS", True, "Já em IECA ou BRA + anlodipino + tiazídico, em doses toleradas, e a meta não veio. K ≤ 4,5 e função renal estável.",
          ["Espironolactona 25 mg: 1 comprimido pela manhã, acrescentada ao esquema que já existe.",
           "Dosar potássio e creatinina em 1 semana e em 4 semanas."],
          "Reavaliar em 4 semanas", "30 comprimidos",
          "Suspender se K ≥ 5,5 ou creatinina subir de forma relevante.",
          "Não acrescentar potássio nem outro poupador.",
          ["espironolactona"], "alta"),
    ],
))

CONDICOES.append(C(
    "dac", "cardiologia", "Doença arterial coronariana estável", "I25",
    ["DAC", "angina estável", "coronariopatia"],
    ["Dor ou aperto no peito aos esforços, que alivia com repouso em poucos minutos", "Equivalente: falta de ar aos esforços"],
    "Quadro típico mais fatores de risco, ou prova isquêmica, ou anatomia já conhecida. Dor em repouso, prolongada ou progressiva é síndrome coronariana aguda, não esta ficha.",
    "Antiagregante se não houver sangramento, estatina, controle da pressão e betabloqueador quando houver infarto prévio ou angina. Nitrato sublingual para a crise. A estatina do básico é a sinvastatina. Atorvastatina está no componente especializado.",
    ["Dor em repouso, suor, náusea, duração maior que 15 minutos: SAMU", "Síncope"],
    ["Não prescrever ácido acetilsalicílico 500 mg por dia", "Não iniciar nitrato de uso contínuo sem pausa e sem afastar uso de inibidor de fosfodiesterase"],
    ["Rename 2024: sinvastatina no básico habitual; atorvastatina só no especializado; dinitrato de isossorbida 5 mg sublingual no básico; AAS 100 mg não foi a apresentação explícita no trecho lido"],
    "media",
    [
        R("dac.fundo", "APS", True, "Angina estável já caracterizada, sem dor no momento, não gestante, sem sangramento.",
          ["Sinvastatina 40 mg: 1 comprimido à noite.",
           "Losartana potássica 50 mg: 1 comprimido pela manhã, se houver hipertensão e o potássio permitir.",
           "Succinato de metoprolol 50 mg: 1 comprimido pela manhã, se a apresentação de liberação prolongada existir no município e não houver broncoespasmo ativo nem ICFEr descompensada.",
           "Ácido acetilsalicílico 100 mg: 1 comprimido ao dia somente se essa apresentação for dispensada. Não substituir por 500 mg ao dia.",
           "Dinitrato de isossorbida 5 mg sublingual: 1 comprimido sentado se a dor de esforço voltar. Se não aliviar em 5 minutos, acionar o SAMU. Não repetir várias vezes em casa."],
          "Uso contínuo; nitrato só na crise", "30 comprimidos de sinvastatina; nitrato em quantidade pequena, com orientação escrita",
          "Confirmar no município a existência de AAS 100 mg e de succinato de metoprolol antes de imprimir essas duas linhas.",
          "Se não houver succinato, atenolol 50 mg pela manhã é a alternativa do básico, sabendo que a evidência pós-infarto é mais fraca.",
          ["sinvastatina", "losartana", "metoprolol_succinato", "aas", "isossorbida"], "media"),
    ],
))

CONDICOES.append(C(
    "icfer", "cardiologia", "Insuficiência cardíaca com fração de ejeção reduzida", "I50",
    ["ICFEr", "ICFER", "coração fraco", "FEVE reduzida"],
    ["Falta de ar aos esforços, ortopneia, edema, cansaço", "Ganho de peso em poucos dias"],
    "Sintomas mais FEVE ≤ 40% no ecocardiograma. O PCDT do SUS trata a terapia padrão e o acesso à dapagliflozina e ao sacubitril/valsartana por critério, não por vontade.",
    "Quatro pilares, introduzidos com o paciente compensado: IECA (enalapril ou captopril), betabloqueador com evidência (carvedilol ou succinato de metoprolol, não atenolol), espironolactona e, se cumprir o PCDT, dapagliflozina 10 mg. Furosemida só se houver congestão. Sacubitril/valsartana substitui o IECA, com pausa de 36 horas, e só nos critérios do componente especializado.",
    ["Falta de ar em repouso, hipotensão, confusão, dor torácica: hospital", "K alto ou creatinina em subida"],
    ["Não associar IECA e BRA", "Não usar atenolol como betabloqueador desta doença", "Não imprimir sacubitril nem dapagliflozina como item do básico"],
    ["Portaria Conjunta que aprova o PCDT de ICFEr, 2024", "Conitec: dapagliflozina 10 mg 1 vez ao dia na ICFEr sintomática NYHA II–IV com FEVE ≤ 40% em terapia padrão", "Rename 2024: carvedilol e espironolactona no básico", "Consenso ACC 2024 para doses inicial e alvo"],
    "alta",
    [
        R("icfer.inicio", "APS", True, "Adulto compensado, PA sistólica em geral ≥ 100 mmHg, K ≤ 5,0, sem congestão importante no dia.",
          ["Maleato de enalapril 5 mg: 1 comprimido de 12 em 12 horas. Alvo usual 10 mg de 12 em 12 horas, dobrando a cada 2 semanas se a pressão e a creatinina permitirem.",
           "Carvedilol 3,125 mg: 1 comprimido de 12 em 12 horas. Dobrar a cada 2 semanas até 25 mg de 12 em 12 horas se o peso for menor que 85 kg. Se o peso for 85 kg ou mais, o alvo usual é 50 mg de 12 em 12 horas, isto é, 2 comprimidos de 25 mg de 12 em 12 horas.",
           "Espironolactona 25 mg: 1 comprimido pela manhã.",
           "Dosar potássio e creatinina em 1 semana e a cada aumento de dose."],
          "Uso contínuo, titulação", "Enalapril 5 mg: 60 comprimidos para 30 dias. Carvedilol 3,125 mg: 60 comprimidos. Espironolactona 25 mg: 30 comprimidos.",
          "Se a PA estiver baixa, começar só o enalapril em 2,5 mg de 12 em 12 horas (meio comprimido de 5 mg, se a bula do produto permitir) e deixar o carvedilol para a semana seguinte.",
          "Captopril 6,25 a 12,5 mg de 8 em 8 horas no lugar do enalapril quando se quer efeito mais curto. Não juntar os dois.",
          ["enalapril", "carvedilol", "espironolactona"], "alta"),
        R("icfer.congestao", "APS", True, "Mesmo paciente, agora com edema ou ortopneia, ainda capaz de ir à UBS e sem hipotensão.",
          ["Furosemida 40 mg: 1 comprimido pela manhã, além do esquema de base.",
           "Pesar-se todo dia. Procurar a unidade se ganhar 2 kg em 3 dias ou se a falta de ar piorar."],
          "Enquanto houver congestão", "30 comprimidos, reavaliar em 7 dias",
          "Não usar furosemida se o paciente está seco só para baixar a pressão.",
          "Se não melhorar em 48 horas ou não conseguir deitar, encaminhar.",
          ["furosemida"], "media"),
        R("icfer.dapagliflozina", "CEAF", False, "Adulto, NYHA II a IV, FEVE ≤ 40%, sintomático, já na terapia padrão. Trâmite do componente especializado.",
          ["Dapagliflozina 10 mg: 1 comprimido pela manhã, se o PCDT e os exames exigidos estiverem completos.",
           "Esta linha não se imprime como receita do componente básico."],
          "Contínuo, com renovação do componente especializado", "Conforme a autorização",
          "Suspender em diarreia, vômito, jejum ou cirurgia. Orientar higiene genital.",
          "Sacubitril/valsartana não entra nesta minuta: exige saída do IECA por 36 horas e critérios próprios de idade, NYHA e BNP.",
          ["dapagliflozina"], "alta"),
    ],
))

CONDICOES.append(C(
    "fa", "cardiologia", "Fibrilação atrial", "I48",
    ["FA", "fibrilação", "arritmia"],
    ["Palpitação irregular, cansaço, falta de ar", "Pode ser achado sem sintoma"],
    "ECG com ausência de onda P e intervalos RR irregulares. Separar instabilidade (dor, edema agudo, hipotensão, isquemia) de FA estável. Calcular o risco de AVC antes de decidir anticoagulação. A varfarina é o anticoagulante do componente básico.",
    "Controle de frequência com betabloqueador se estável. Anticoagulação com varfarina e INR quando o risco embólico justificar e houver quem dose o INR. Não imprimir anticoagulante oral direto como item do básico: não apareceu nessa leitura da Rename 2024.",
    ["Instabilidade, dor torácica, síncope: hospital", "INR sem controle não autoriza renovar varfarina no escuro"],
    ["Não cardioverter na UBS", "Não usar AAS no lugar de anticoagulante para prevenir AVC na FA"],
    ["Rename 2024: varfarina 1 mg e 5 mg no básico", "Diretriz Brasileira de Hipertensão 2025 e prática de FA: betabloqueador para frequência"],
    "media",
    [
        R("fa.frequencia", "APS", True, "FA estável, frequência em geral acima de 110 em repouso, sem insuficiência cardíaca descompensada e sem broncoespasmo.",
          ["Atenolol 50 mg: 1 comprimido pela manhã.",
           "Reavaliar a frequência em 1 semana. Alvo de repouso em geral abaixo de 110 no início, mais baixo se o paciente seguir sintomático."],
          "Reavaliar em 7 dias", "30 comprimidos",
          "Se houver ICFEr, usar carvedilol do esquema da ICFEr, não atenolol.",
          "Succinato de metoprolol 50 mg pela manhã se a apresentação existir.",
          ["atenolol"], "media"),
        R("fa.varfarina", "APS", True, "Indicação de anticoagulação já definida pelo prescritor, serviço com INR, sem gestação, sem sangramento ativo.",
          ["Varfarina sódica 5 mg: 1 comprimido à noite por 2 dias, se adulto sem fragilidade.",
           "Se 75 anos ou mais, baixo peso ou hepatopatia, começar com 2,5 mg (meio comprimido de 5 mg, se o produto permitir partir) ou com o comprimido de 1 mg, conforme a experiência do serviço.",
           "INR no 4º dia. Alvo 2,0 a 3,0. Não renovar sem INR recente."],
          "Contínuo, guiado por INR", "Não entregar caixa fechada sem data de retorno do INR",
          "Antibiótico, amiodarona e mudança de dieta alteram o INR. Avisar a farmácia e o laboratório.",
          "Não há receita pronta de rivaroxabana ou apixabana neste elenco básico.",
          ["varfarina"], "media"),
    ],
))

CONDICOES.append(C(
    "iam", "cardiologia", "Infarto agudo do miocárdio", "I21",
    ["IAM", "infarto", "ataque cardíaco", "síndrome coronariana aguda"],
    ["Dor ou aperto no peito em repouso, prolongada", "Suor, náusea, falta de ar, irradiação para braço ou mandíbula"],
    "ECG em até 10 minutos onde houver desfibrilador e quem saiba ler. Supra de ST é transferência imediata. Esta ficha não trombolisa.",
    "Acionar o SAMU. Se não houver alergia nem sangramento ativo, ácido acetilsalicílico 200 a 300 mg para mastigar enquanto o transporte chega. O restante do tratamento é hospitalar.",
    ["Parada, hipotensão, edema agudo de pulmão"],
    ["Não aplicar trombolítico na UBS sem protocolo escrito e sem ECG", "Não reter o paciente para completar exames"],
    ["Via aberta do infarto: tempo até a reperfusão. Rename não transforma a UBS em sala de hemodinâmica."],
    "alta",
    [
        R("iam.samu", "EMERGENCIA", False, "Suspeita de infarto.",
          ["Acionar o SAMU.",
           "Ácido acetilsalicílico 200 a 300 mg para mastigar, se não houver alergia a AAS e não houver sangramento ativo.",
           "Se só existir comprimido de 500 mg, não improvisar a dose: registrar o que foi dado e não repetir.",
           "Oxigênio só se a saturação estiver baixa. Não há morfina de rotina nesta minuta."],
          "Até a chegada do transporte", "Não é receita para casa",
          "Alergia e sangramento ativo impedem o AAS.",
          "Nenhuma.",
          ["aas"], "alta"),
    ],
))

CONDICOES.append(C(
    "crise_has", "cardiologia", "Crise hipertensiva", "I16",
    ["urgência hipertensiva", "emergência hipertensiva", "pressão muito alta"],
    ["PA muito alta com ou sem dor no peito, falta de ar, déficit, rebaixamento"],
    "Emergência é PA em geral ≥ 180/120 com lesão aguda de órgão. Urgência é o número alto sem essa lesão. O número sozinho não manda baixar a pressão em minutos.",
    "Emergência vai ao hospital, com queda controlada. Urgência sem lesão: ambiente calmo, retomar o anti-hipertensivo que o paciente já usa, observar e marcar retorno breve. Não há nifedipina de cápsula para morder.",
    ["Dor torácica, déficit, dispneia, eclâmpsia, dissecção"],
    ["Não usar nifedipina de ação rápida", "Não baixar a PA à força em AVC sem protocolo de UTI"],
    ["Diretriz Brasileira de Hipertensão Arterial 2025"],
    "alta",
    [
        R("crise.urgencia", "APS", False, "PA alta, exame sem lesão aguda, paciente conhecido e já medicado.",
          ["Repetir a medida após 15 minutos, sentado, com manguito certo.",
           "Se confirmar e não houver lesão, retomar a medicação habitual que ele deixou de tomar e observar.",
           "Retorno em 24 a 72 horas. Se surgir dor, falta de ar ou déficit, hospital."],
          "Observação curta", "Sem fármaco novo de ação rápida",
          "Captopril pode ser usado por quem já tem protocolo local escrito. Não fixo dose aqui.",
          "Nenhuma cápsula sublingual.",
          [], "alta"),
    ],
))

# infecção
CONDICOES.append(C(
    "pac", "infeccao", "Pneumonia adquirida na comunidade", "J18",
    ["PAC", "pneumonia", "pulmão"],
    ["Tosse, febre, escarro, dor pleurítica, falta de ar", "Confusão no idoso"],
    "Quadro agudo mais achado focal no exame ou na imagem. CRB-65: confusão, frequência respiratória ≥ 30, PA baixa, 65 anos ou mais. Zero a 1, sem comorbidade grave, pode ser ambulatorial. A partir de 3, hospital.",
    "Amoxicilina é o Access do básico. Azitromicina é Watch e não é a primeira linha de todo mundo. No hospital, ceftriaxona mais azitromicina. Duração mínima clássica de 5 dias, interromper quando estável.",
    ["Saturação baixa, FR ≥ 30, hipotensão, confusão", "Não melhora em 48–72 horas"],
    ["Não usar ciprofloxacino como rotina", "Não tratar gripe sem foco como pneumonia"],
    ["IDSA/ATS 2019: amoxicilina 1 g de 8/8 h no ambulatorial sem comorbidade; betalactâmico mais macrolídeo no hospital; duração ≥ 5 dias se estável", "Protocolo municipal de Ribeirão Preto: amoxicilina 500 mg de 8/8 h por 5 a 7 dias no CRB-65 0–1", "Rename 2024: amoxicilina 500 mg, azitromicina 500 mg, ceftriaxona 1 g"],
    "media",
    [
        R("pac.ubs", "APS", True, "Adulto, CRB-65 0 ou 1, come e bebe, saturação preservada, sem imunossupressão.",
          ["Amoxicilina 500 mg: 2 comprimidos de 8 em 8 horas, por 5 dias. Dose do dia: 3 g, alinhada à IDSA.",
           "Se não tolerar 1 g por tomada, amoxicilina 500 mg: 1 comprimido de 8 em 8 horas, por 5 a 7 dias, como no protocolo municipal citado.",
           "Retorno em 48 horas se a febre ou a falta de ar piorarem. Antes disso, procurar urgência se surgir o alarme."],
          "5 dias", "30 comprimidos de 500 mg no esquema de 1 g",
          "Alongar o intervalo na TFG baixa. Não manter 1 g de 8 em 8 horas na DRC avançada sem recalcular. Alergia imediata a penicilina: não usar esta linha. Azitromicina 500 mg, 1 comprimido ao dia por 3 dias, sabendo que é Watch e que há resistência de pneumococo a macrolídeo.",
          "Com comorbidade (DPOC, diabetes, cardiopatia) e ainda ambulatorial: amoxicilina + clavulanato 500 mg + 125 mg, 1 comprimido de 8 em 8 horas, por 7 dias. Azitromicina só se o protocolo local pedir cobertura de atípico.",
          ["amoxicilina"], "media"),
        R("pac.hospital", "HOSPITAL", False, "CRB-65 ≥ 2 ou hipoxemia. Não imprimir para casa.",
          ["Ceftriaxona 1 g, intravenosa, 1 vez ao dia. Protocolos locais usam 2 g (dois frascos de 1 g).",
           "Azitromicina 500 mg, via oral, 1 vez ao dia.",
           "Rever em 48 horas e suspender ao completar 5 dias se estiver estável: sem febre, FR < 24, FC < 100, pressão estável, comendo, lúcido."],
          "Pelo menos 5 dias", "Uso hospitalar",
          "Cobertura de MRSA ou Pseudomonas só com fator de risco local, não de rotina.",
          "Nenhuma receita oral equivalente para o paciente grave.",
          ["ceftriaxona", "azitromicina"], "media"),
    ],
))

CONDICOES.append(C(
    "diverticulite", "infeccao", "Diverticulite aguda", "K57",
    ["diverticulite", "dor na fossa ilíaca esquerda"],
    ["Dor na fossa ilíaca esquerda, febre baixa, alteração do hábito intestinal"],
    "Clínica. Tomografia se dúvida, imunossupressão, piora ou suspeita de abscesso. Diverticulite não complicada em pessoa hígida pode dispensar antibiótico, com reavaliação precoce.",
    "Se for usar antibiótico no ambulatorial estável: amoxicilina + clavulanato na apresentação 500/125 do SUS, por 5 a 7 dias. Abscesso, peritonite e sepse são hospital e dreno, não receita.",
    ["Defesa abdominal, vômito incoercível, sepse", "Sem melhora em 48–72 horas"],
    ["Não usar ciprofloxacino de rotina", "Não operar a dieta zero por dias em casa"],
    ["Rename 2024: amoxicilina + clavulanato 500 mg + 125 mg", "Evidência de que o antibiótico pode ser omitido na não complicada imunocompetente"],
    "media",
    [
        R("div.ubs", "APS", True, "Dor localizada, sem peritonite, come e bebe, sem imunossupressão, reavaliação garantida em 48 horas.",
          ["Dieta leve. Analgésico: paracetamol 500 mg, 1 a 2 comprimidos a cada 6 horas, sem passar de 3 g por dia.",
           "Se o prescritor decidir por antibiótico: amoxicilina + clavulanato 500 mg + 125 mg, 1 comprimido de 8 em 8 horas, por 5 dias, estendendo a 7 se a resposta for lenta.",
           "Retorno obrigatório em 48 horas."],
          "5 a 7 dias se usar antibiótico", "15 a 21 comprimidos de 500/125",
          "Alergia a penicilina: não trocar por ciprofloxacino nesta minuta. Encaminhar.",
          "Sem antibiótico, só analgesia e retorno, é conduta válida no hígido.",
          ["amox_clav", "paracetamol"], "media"),
    ],
))

CONDICOES.append(C(
    "colecistite", "infeccao", "Colecistite aguda", "K81",
    ["colecistite", "vesícula"],
    ["Dor no hipocôndrio direito, contínua, febre, Murphy"],
    "Ultrassom. É doença cirúrgica. Antibiótico não substitui a colecistectomia precoce.",
    "Encaminhar. Jejum relativo até a avaliação. Antibiótico venoso fica no hospital.",
    ["Icterícia, hipotensão, confusão: pensar colangite", "Defesa abdominal"],
    ["Não tratar colecistite aguda só com comprimido em casa"],
    ["Tóquio e prática cirúrgica: colecistectomia precoce na colecistite calculosa aguda"],
    "alta",
    [R("cole.hospital", "HOSPITAL", False, "Colecistite aguda.",
       ["Encaminhar para cirurgia no mesmo dia.",
        "Não redigir antibiótico oral como tratamento definitivo.",
        "No hospital, o esquema habitual cobre gram-negativo e anaeróbio, por exemplo ceftriaxona associada a metronidazol, até a fonte ser controlada. A dose do metronidazol venoso depende da apresentação do hospital."],
       "Até a cirurgia", "Sem receita de UBS", "Ajustar ao protocolo da CCIH.", "Nenhuma.", ["ceftriaxona"], "media")],
))

CONDICOES.append(C(
    "abscesso_abd", "infeccao", "Abscesso abdominal", "K65",
    ["abscesso abdominal", "coleção"],
    ["Febre, dor abdominal, massa, íleo"],
    "Imagem. Coleção que comporta dreno não cura com antibiótico isolado.",
    "Drenagem percutânea ou cirúrgica mais antibiótico depois da cultura. UBS não trata.",
    ["Sepse, peritonite"],
    ["Não prescrever antibiótico oral por 14 dias no lugar do dreno"],
    ["Controle da fonte é o tratamento"],
    "alta",
    [R("abs.dreno", "HOSPITAL", False, "Coleção intra-abdominal.",
       ["Solicitar imagem e drenagem.",
        "Hemocultura se febre.",
        "Antibiótico venoso só como ponte até o dreno e a cultura, pelo protocolo da CCIH."],
       "Definida pela cirurgia", "Sem receita de UBS", "Sem dreno, o antibiótico falha.", "Nenhuma.", [], "alta")],
))

CONDICOES.append(C(
    "celulite", "infeccao", "Celulite e erisipela", "L03",
    ["celulite", "erisipela", "infecção de pele"],
    ["Placa quente, dolorosa, vermelha", "Erisipela tem borda nítida e acomete mais a derme"],
    "Clínico. Marcar a borda com caneta. Procurar porta de entrada. Purulenta (abscesso) pede abertura. Necrose, bolha hemorrágica, dor desproporcional e crepitação são emergência cirúrgica.",
    "Não purulenta, estável: cefalexina por 5 dias. Rever a marca da borda em 48 horas.",
    ["Sepse, necrose, mão ou face com progressão rápida, imunossupressão"],
    ["Não usar antibiótico tópico como tratamento de celulite", "Não alongar para 14 dias se a borda recuou em 5"],
    ["Rename 2024: cefalexina 500 mg", "IDSA de pele: 5 dias na celulite não complicada que melhora"],
    "media",
    [R("cel.ubs", "APS", True, "Celulite não purulenta, estável, sem necrose, adulto não gestante.",
       ["Cefalexina 500 mg: 1 comprimido de 6 em 6 horas, por 5 dias.",
        "Elevar o membro. Tratar a porta de entrada.",
        "Retorno em 48 horas com a marca da borda."],
       "5 dias", "20 comprimidos",
       "Alergia imediata a penicilina ou cefalosporina: não improvisar clindamicina aqui. Reavaliar presencialmente.",
       "Se houver abscesso, abrir. Antibiótico só se houver celulite ao redor.",
       ["cefalexina"], "media")],
))

CONDICOES.append(C(
    "ferida", "infeccao", "Infecção de ferida operatória", "T81.4",
    ["ISO", "ferida operatória", "deiscência infectada"],
    ["Eritema, calor, saída de secreção, dor na incisão, em geral após o 3º dia"],
    "Abrir o ponto que está tenso, esvaziar, cultura se houver secreção. Antibiótico só se houver celulite ao redor ou sinal sistêmico. Prótese, cavidade e fáscia são centro cirúrgico.",
    "Ferida superficial estável com celulite limitada: mesma cefalexina da celulite, depois de abrir. O resto encaminha.",
    ["Febre alta, crepitação, evisceração, prótese"],
    ["Não fechar de novo uma ferida infectada", "Não dar antibiótico sem olhar a ferida"],
    ["Controle da fonte na infecção de sítio cirúrgico"],
    "alta",
    [R("ferida.superficial", "APS", True, "Incisão superficial já aberta e drenada, celulite pequena ao redor, sem prótese, sem fáscia aberta, estável.",
       ["Curativo com limpeza e gaze, sem ocluir a ponto de reter pus.",
        "Cefalexina 500 mg: 1 comprimido de 6 em 6 horas, por 5 dias.",
        "Retorno em 48 horas."],
       "5 dias", "20 comprimidos",
       "Se a secreção for de cavidade ou a fáscia estiver exposta, esta receita não vale.",
       "Sem celulite e sem febre, abrir e curativo podem bastar, sem antibiótico.",
       ["cefalexina"], "media")],
))

CONDICOES.append(C(
    "sepse", "infeccao", "Sepse", "A41",
    ["sepse", "choque séptico", "infecção generalizada"],
    ["Infecção mais disfunção: hipotensão, confusão, falta de ar, oligúria, lactato alto"],
    "Infecção suspeita mais disfunção orgânica. Choque é hipotensão que precisa de vasopressor. Não existe um antibiótico único.",
    "Hospital. Cultura antes do antibiótico se isso não atrasar a primeira dose. Cristaloide em bolus reavaliado, não um volume cego. Noradrenalina se o choque permanecer. O antibiótico segue o foco e o protocolo da CCIH. O valor clássico de 30 mL/kg é referência de hipoperfusão e deve ser reavaliado a cada etapa.",
    ["Hipotensão, confusão, queda de urina"],
    ["Não mandar sepse para casa com comprimido", "Não escolher antibiótico sem foco e sem protocolo local"],
    ["Surviving Sepsis, com a ressalva de individualizar o volume"],
    "alta",
    [R("sepse.pacote", "HOSPITAL", False, "Sepse ou choque.",
       ["Reconhecer e não reter na UBS.",
        "Lactato, hemocultura se não atrasar, antibiótico da CCIH conforme o foco, cristaloide com reavaliação, vasopressor se o choque permanecer.",
        "Controle da fonte no mesmo tempo: dreno, cirurgia, cateter, via biliar."],
       "Imediato", "Sem receita", "Sem peso e sem foco, não há dose nesta ficha.", "Nenhuma.", [], "alta")],
))

CONDICOES.append(C(
    "endocardite", "infeccao", "Endocardite infecciosa", "I33",
    ["endocardite", "vegetação"],
    ["Febre persistente, sopro novo, fenômeno embólico, peteóquia, em quem usa droga injetável ou tem prótese valvar"],
    "Critérios de Duke. Três pares de hemocultura antes do antibiótico, de veias diferentes. Ecocardiograma. Não se trata com receita pronta sem o germe.",
    "Internar. Antibiótico venoso dirigido pela cultura e pela válvula nativa ou protética. Esta ficha não traz esquema empírico para imprimir.",
    ["Choque, embolia, bloqueio cardíaco, insuficiência valvar aguda"],
    ["Não iniciar antibiótico oral na UBS antes das hemoculturas se a suspeita for forte e a transferência for imediata"],
    ["Duke e antibioticoterapia dirigida"],
    "alta",
    [R("endo.internar", "HOSPITAL", False, "Suspeita de endocardite.",
       ["Internar. Três pares de hemocultura. Ecocardiograma.",
        "Avisar a infectologia. Não há receita oral."],
       "Semanas, venoso, dirigido", "Sem receita", "Prótese e valva nativa não usam o mesmo esquema.", "Nenhuma.", [], "alta")],
))

CONDICOES.append(C(
    "fistula", "infeccao", "Fístula com queixa vaginal", "N82",
    ["fístula retovaginal", "vaginite por fístula", "perda de fezes pela vagina"],
    ["Saída de gases ou fezes pela vagina, corrimento fétido, infecção urinária de repetição"],
    "Não é vaginite. Examinar e pensar em fístula retovaginal ou enterovaginal, muitas vezes pós-operatória, obstétrica, actínica ou por doença de Crohn ou tumor.",
    "A fístula fecha com correção da causa, não com creme. Antibiótico só se houver celulite ou abscesso. Encaminhar à cirurgia ou à ginecologia. Proteger a pele. Não prescrever metronidazol tópico como tratamento.",
    ["Abscesso, sepse, obstrução"],
    ["Não rotular como vaginose e dispensar"],
    ["A via de tratamento é o fechamento ou a derivação do trânsito, conforme a cirurgia"],
    "alta",
    [R("fistula.enc", "ENCAMINHAMENTO", False, "Suspeita de fístula.",
       ["Exame especular e toque. Não presumir vaginite.",
        "Encaminhar para quem opera fístula. Cuidado de pele com barreira.",
        "Metronidazol não fecha fístula."],
       "Até a avaliação cirúrgica", "Sem antibiótico empírico", "Se houver coleção, vale a ficha de abscesso.", "Nenhuma.", [], "alta")],
))

CONDICOES.append(C(
    "colangite", "infeccao", "Colangite aguda", "K83.0",
    ["colangite", "via biliar infectada"],
    ["Dor no hipocôndrio direito, febre, icterícia. Hipotensão e confusão marcam o quadro grave."],
    "Tríade de Charcot não está sempre completa. Gravidade pelos critérios de Tóquio. A fonte é a obstrução da via biliar.",
    "Antibiótico venoso e descompressão da via biliar. Não há receita oral definitiva.",
    ["Hipotensão, confusão, falência de órgão"],
    ["Não tratar icterícia febril com comprimido em casa"],
    ["Critérios de Tóquio: antibiótico mais drenagem"],
    "alta",
    [R("colangite.hosp", "HOSPITAL", False, "Colangite.",
       ["Hospital no mesmo dia. Hemocultura. Antibiótico venoso que cubra gram-negativo e anaeróbio, pelo protocolo local.",
        "Descompressão por CPRE ou alternativa se a resposta não for imediata ou se o grau for moderado ou grave."],
       "Até drenar", "Sem receita de UBS", "A dose não se fixa sem o protocolo da CCIH.", "Nenhuma.", ["ceftriaxona"], "media")],
))

CONDICOES.append(C(
    "empiema", "infeccao", "Empiema pleural", "J86",
    ["empiema", "pus no peito"],
    ["Pneumonia que não melhora, febre persistente, derrame"],
    "Toracocentese. Pus, pH baixo ou germe no líquido é empiema. Derrame parapneumônico simples não é empiema.",
    "Dreno pleural mais antibiótico. Antibiótico sem dreno não trata empiema.",
    ["Desconforto respiratório, sepse"],
    ["Não puncionar e mandar para casa", "Não tratar como pneumonia oral"],
    ["Drenagem é obrigatória no empiema"],
    "alta",
    [R("empiema.dreno", "HOSPITAL", False, "Empiema.",
       ["Internar. Dreno. Cultura do líquido.",
        "Antibiótico venoso cobrindo coco e anaeróbio, pelo protocolo, até o controle da fonte. A duração segue a cirurgia e a melhora, não um número fixo de comprimidos."],
       "Hospitalar", "Sem receita", "Sem dreno não há tratamento.", "Nenhuma.", [], "alta")],
))

CONDICOES.append(C(
    "otomastoidite", "infeccao", "Otomastoidite", "H70",
    ["mastoidite", "otomastoidite"],
    ["Otalgia, febre, abaulamento retroauricular, orelha deslocada para a frente, depois de otite"],
    "Clínico. Tomografia se dúvida ou complicação. É urgência otorrinolaringológica, com risco de abscesso e de complicação intracraniana.",
    "Hospital, antibiótico venoso e avaliação do otorrino no mesmo dia. Não tratar como otite com comprimido.",
    ["Cefaleia intensa, rigidez, paralisia facial, confusão"],
    ["Não dar amoxicilina e marcar retorno em uma semana"],
    ["Complicação de otite média: drenagem pode ser necessária"],
    "alta",
    [R("masto.hosp", "HOSPITAL", False, "Otomastoidite.",
       ["Encaminhar no mesmo dia ao hospital com otorrino.",
        "Antibiótico venoso lá, não aqui."],
       "Hospitalar", "Sem receita", "Paralisia facial ou sinal neurológico é emergência.", "Nenhuma.", [], "alta")],
))

CONDICOES.append(C(
    "dm2", "endocrinologia", "Diabetes mellitus tipo 2", "E11",
    ["DM2", "diabetes", "açúcar alto"],
    ["Sede, urina em excesso, emagrecimento, visão turva", "Muitas vezes não há sintoma"],
    "Jejum ≥ 126, ou HbA1c ≥ 6,5 com método padronizado, ou 2 horas no teste oral ≥ 200, ou aleatória ≥ 200 com sintomas. Em quem não tem sintoma, repetir. Rastrear a partir dos 35 anos ou antes se houver obesidade e outro fator. Meta usual: HbA1c ≤ 7%, jejum 80 a 130. Idoso frágil: meta mais folgada, evitar hipoglicemia.",
    "Medida de vida em todos. Metformina é a primeira linha, titulada até a maior dose tolerada, com teto renal. Se a HbA1c inicial estiver acima de 7,5%, a SBD aceita já associar sulfonilureia para não perder tempo; a preferida é a gliclazida, não a glibenclamida. Dapagliflozina 10 mg só com critério do componente especializado. Insulina NPH à noite quando o oral otimizado falha ou a glicemia está muito alta.",
    ["Cetoacidose, vômito, sonolência, glicemia muito alta com desidratação: hospital", "Hipoglicemia com sulfonilureia ou insulina"],
    ["Não começar glibenclamida em idoso ou DRC", "Não manter metformina se TFG < 30 ou em doença aguda desidratante"],
    ["SBD 2026, capítulo do DM2 no SUS, citando o PCDT de fevereiro de 2026", "Metformina: máximo 1000 mg/dia se TFG < 45 e suspender se < 30", "NPH: 10 UI ou 0,2 UI/kg à noite, ajuste de 2 a 4 UI", "Gliclazida 30 a 120 mg/dia na tabela da SBD 2024"],
    "alta",
    [
        R("dm2.metformina", "APS", True, "DM2 recém-confirmado, TFG ≥ 45, sem doença aguda, não gestante.",
          ["Cloridrato de metformina 500 mg: 1 comprimido no jantar por 7 dias.",
           "Se tolerar, 1 comprimido no almoço e 1 no jantar.",
           "Se a meta não vier, titular até 850 mg de 12 em 12 horas, sem passar de 2 g por dia no total e sem passar de 1000 mg por dia se a TFG estiver entre 30 e 44. Suspender se a TFG for menor que 30.",
           "HbA1c em 3 meses."],
          "Contínuo", "Começar com 30 comprimidos de 500 mg e reavaliar a titulação",
          "Orientar a parar a metformina se houver vômito, diarreia intensa ou contraste.",
          "Se não tolerar nem 500 mg, não insistir. A apresentação de liberação prolongada da Farmácia Popular pode ser tentada se existir.",
          ["metformina"], "alta"),
        R("dm2.su", "APS", True, "Metformina já na maior dose tolerada e HbA1c ainda acima da meta. Ou HbA1c inicial acima de 7,5%, junto com a metformina.",
          ["Gliclazida 30 mg: 1 comprimido pela manhã, junto com a metformina.",
           "Pode subir até 120 mg por dia conforme a resposta, em geral a cada 4 semanas.",
           "Orientar hipoglicemia: tremor, suor, fome. Tomar açúcar e procurar a unidade se repetir."],
          "Reavaliar em 4 a 12 semanas", "30 comprimidos de 30 mg",
          "Não usar glibenclamida se o paciente for idoso ou tiver DRC.",
          "Glibenclamida 2,5 a 5 mg pela manhã só se a gliclazida não existir e o paciente for jovem, com função renal boa. Teto citado: 20 mg/dia.",
          ["gliclazida"], "alta"),
        R("dm2.insulina", "APS", True, "Oral otimizado sem meta, ou glicemia de jejum persistentemente alta, paciente capaz de aplicar e reconhecer hipoglicemia.",
          ["Insulina humana NPH 100 UI/mL: 10 unidades por via subcutânea à noite, ou 0,2 UI por kg se o prescritor preferir calcular pelo peso.",
           "Medir a glicemia de jejum. Ajustar 2 a 4 unidades a cada poucos dias até o jejum entrar na meta, sem hipoglicemia.",
           "Manter a metformina se a TFG permitir."],
          "Contínuo, com ajuste", "Frasco ou tubete conforme a farmácia, mais seringas ou agulhas",
          "Não iniciar sem alguém que saiba aplicar e sem orientação de hipoglicemia.",
          "A insulina regular entra depois, se o pós-prandial seguir alto com a NPH já ajustada. Não escrever as duas no primeiro dia.",
          ["insulina_nph", "metformina"], "alta"),
        R("dm2.dapa", "CEAF", False, "Critério do componente especializado ou da Farmácia Popular, conforme a faixa etária e o risco cardiovascular ou renal do PCDT.",
          ["Dapagliflozina 10 mg: 1 comprimido pela manhã, só depois de cumprir o critério escrito no PCDT.",
           "Não substitui a metformina por conta própria."],
          "Conforme a autorização", "Não é receita do básico",
          "Parar em doença aguda. Orientar infecção genital e cetoacidose.",
          "Ler o quadro de elegibilidade da SBD 2026 antes de prometer o fármaco.",
          ["dapagliflozina"], "alta"),
    ],
))

CONDICOES.append(C(
    "hipotireoidismo", "endocrinologia", "Hipotireoidismo", "E03.9",
    ["tireoide baixa", "hipotireoidismo", "TSH alto"],
    ["Cansaço, frio, pele seca, constipação, ganho de peso", "Pode ser só laboratorial"],
    "TSH elevado com T4 livre baixo confirma o franco. TSH alto com T4 livre normal é subclínico: tratar se TSH em geral ≥ 10, se houver sintoma, gestação ou tentativa de engravidar. Confirmar em segunda amostra se não houver sintoma.",
    "Levotiroxina em jejum. Adulto jovem e saudável: cerca de 1,6 mcg/kg/dia. Idoso ou coronariopata: 12,5 a 25 mcg e subir devagar. Novo TSH em 6 a 8 semanas. Não ajustar antes disso.",
    ["Mixedema, bradicardia extrema, hipotermia: hospital"],
    ["Não tomar junto com cálcio, ferro ou café", "Não subir a dose toda semana"],
    ["Prática de reposição com levotiroxina. Apresentações de 12,5 a 100 mcg constam de elenco do básico."],
    "media",
    [R("hipot.adulto", "APS", True, "Hipotireoidismo franco, adulto com menos de 60 anos, sem coronariopatia conhecida, não gestante.",
       ["Levotiroxina sódica: dose inicial próxima de 1,6 mcg por kg, arredondada para a apresentação que existe (25, 50 ou 100 mcg).",
        "1 comprimido em jejum, com água, 30 a 60 minutos antes do café.",
        "TSH em 6 a 8 semanas. Não mudar a dose antes."],
       "Contínuo", "30 comprimidos da apresentação escolhida",
       "Se 60 anos ou mais, ou angina prévia: começar com 25 mcg, ou 12,5 mcg se houver apresentação, e subir a cada 6 a 8 semanas.",
       "Separar 4 horas de cálcio, ferro e omeprazol.",
       ["levotiroxina"], "media")],
))

CONDICOES.append(C(
    "dislipidemia", "endocrinologia", "Dislipidemia", "E78",
    ["colesterol", "LDL", "triglicerídeo"],
    ["Sem sintoma até o evento", "Xantoma é tardio e raro"],
    "Perfil lipídico em jejum quando se vai decidir estatina. O alvo depende do risco, não de um número único para todo mundo. Prevenção secundária (infarto, AVC, revascularização) tem prioridade.",
    "No componente básico a estatina disponível de rotina é a sinvastatina, à noite, 20 a 40 mg. Atorvastatina 40 ou 80 mg, que é alta intensidade, está no componente especializado e não se imprime como básico.",
    ["Dor muscular intensa com urina escura: suspender e dosar CK"],
    ["Não usar estatina na gestação", "Não prometer atorvastatina do básico"],
    ["Rename 2024: atorvastatina no especializado. Sinvastatina 10, 20 e 40 mg no elenco básico habitual."],
    "media",
    [R("lip.sinva", "APS", True, "Adulto com indicação de estatina, sem gestação, sem hepatopatia ativa.",
       ["Sinvastatina 20 mg: 1 comprimido à noite.",
        "Se prevenção secundária e a sinvastatina for a única opção do básico, usar 40 mg à noite e registrar que a alta intensidade depende do componente especializado.",
        "Transaminase se houver sintoma hepático. CK se houver dor muscular."],
       "Contínuo", "30 comprimidos",
       "Não associar a fibrato de rotina.",
       "Atorvastatina só pelo fluxo do especializado.",
       ["sinvastatina"], "media")],
))

CONDICOES.append(C(
    "sm", "endocrinologia", "Síndrome metabólica", "E88.81",
    ["síndrome metabólica", "resistência insulínica"],
    ["Cintura aumentada, pressão alta, glicemia ou triglicerídeo altos, HDL baixo"],
    "Três ou mais componentes, conforme o critério adotado pelo serviço. Não é uma doença com um comprimido próprio.",
    "Tratar cada componente com a ficha correspondente e mudar comida e movimento. Perda de 5 a 7% do peso quando houver sobrepeso.",
    ["Evento cardiovascular agudo"],
    ["Não criar uma receita única de síndrome metabólica"],
    ["SBD 2026: estilo de vida é a base da prevenção do diabetes"],
    "alta",
    [R("sm.base", "APS", False, "Síndrome metabólica sem descompensação.",
       ["Caminhada progressiva até 150 minutos por semana.",
        "Comida com menos ultraprocessado. Não há fármaco desta ficha.",
        "Abrir as fichas de HAS, DM2 e dislipidemia se cada uma estiver presente."],
       "Contínuo", "Sem receita própria", "Metformina na prevenção do diabetes só nas situações da SBD, não para todo mundo.", "Nenhuma.", [], "alta")],
))

CONDICOES.append(C(
    "vitd", "endocrinologia", "Deficiência de vitamina D", "E55",
    ["vitamina D baixa", "25-OH"],
    ["Em geral sem sintoma", "Dor óssea e fraqueza se a falta for grande"],
    "25-hidroxivitamina D. Abaixo de 20 ng/mL é deficiência na maioria dos consensos. Não dosar em todo mundo sem indicação: osteoporose, queda, má absorção, DRC, idoso institucionalizado, sintoma.",
    "Repor colecalciferol e manter. Não fixo ataque de 50.000 UI porque essa apresentação não foi confirmada na Rename nesta leitura. Usar a apresentação que o município dispensa e a dose de manutenção de 800 a 2.000 UI por dia depois da reposição.",
    ["Cálcio muito baixo com tetania: hospital"],
    ["Não empilhar cálcio e vitamina D sem olhar o cálcio sérico na DRC"],
    ["Limiar de 20 ng/mL é o mais usado para deficiência. Apresentação do SUS a conferir no município."],
    "baixa",
    [R("vitd.manut", "APS", True, "Deficiência confirmada, cálcio sérico normal, não gestante.",
       ["Colecalciferol na apresentação do município: dose de manutenção 800 a 2.000 UI por dia, com a maior refeição.",
        "Se o serviço tiver protocolo escrito de ataque, seguir esse protocolo. Não inventar 50.000 UI.",
        "Nova dosagem em 3 meses se a falta era importante."],
       "Manutenção prolongada se o risco continuar", "Conforme a apresentação local",
       "Na DRC, combinar com o nefrologista antes de dose alta.",
       "Sol e comida não corrigem deficiência já instalada em quem tem osteoporose.",
       [], "baixa")],
))

CONDICOES.append(C(
    "osteo", "endocrinologia", "Osteoporose", "M81",
    ["osteoporose", "osso fraco"],
    ["Sem sintoma até a fratura", "Perda de altura, cifose"],
    "Densitometria ou fratura por fragilidade. Antes do bisfosfonato: cálcio sérico, função renal, vitamina D, boca.",
    "Alendronato 70 mg uma vez por semana está no básico. Não usar se TFG < 35. Corrigir vitamina D antes. Cálcio de preferência na comida.",
    ["Fratura aguda: ortopedia", "Dor na coxa ou na mandíbula em quem já usa bisfosfonato"],
    ["Não deitar depois do comprimido", "Não usar com TFG < 35"],
    ["Rename 2024: alendronato 70 mg e 10 mg no básico"],
    "alta",
    [R("osteo.alen", "APS", True, "Osteoporose confirmada, TFG ≥ 35, vitamina D em reposição, capaz de ficar em pé 30 minutos, sem problema esofágico.",
       ["Alendronato de sódio 70 mg: 1 comprimido uma vez por semana, em jejum, com um copo de água.",
        "Ficar em pé ou sentado ereto por 30 minutos. Não deitar. Não comer nesse intervalo.",
        "Manter a vitamina D da ficha própria.",
        "Rever em 1 ano e planejar pausa conforme a evolução, em geral após alguns anos."],
       "Semanal, contínuo com data para reavaliar", "4 comprimidos por mês",
       "Se não tolerar semanal, alendronato 10 mg pela manhã, no mesmo ritual.",
       "Cálcio em comprimido só se a comida não alcançar e o cálcio sérico for normal.",
       ["alendronato"], "alta")],
))

CONDICOES.append(C(
    "obesidade", "endocrinologia", "Obesidade", "E66",
    ["obesidade", "IMC alto"],
    ["IMC ≥ 30, ou ≥ 25 com comorbidade, no critério usual do adulto"],
    "Peso, altura, cintura, pressão, glicemia e lipídios. Procurar causa de ganho rápido: hipotireoidismo, corticoide, edema.",
    "Comida e movimento são o tratamento do básico. Não há receita pronta de sibutramina, orlistate ou semaglutida neste elenco: não foram confirmados como item livre do componente básico nesta leitura.",
    ["Dispneia, apneia grave, IMC muito alto com limitação: avaliar serviço de referência"],
    ["Não prescrever anfetamina nem hormônio tireoidiano para emagrecer"],
    ["SBD: perda de 5 a 7% do peso na prevenção do diabetes"],
    "alta",
    [R("obes.vida", "APS", False, "Obesidade sem descompensação.",
       ["Meta inicial: perder 5 a 7% do peso em meses, não em semanas.",
        "150 minutos de atividade por semana, conforme a junta permitir.",
        "Sem fármaco nesta minuta."],
       "Contínuo", "Sem receita", "Fármaco de obesidade só se um PCDT vigente o entregar. Conferir antes.", "Nenhuma.", [], "alta")],
))

CONDICOES.append(C(
    "siadh", "endocrinologia", "SIADH", "E22.2",
    ["SIADH", "sódio baixo", "hiponatremia euvolêmica"],
    ["Náusea, cefaleia, confusão, queda. Convulsão se o sódio cair rápido."],
    "Hiponatremia euvolêmica, urina concentrada, sódio urinário alto, com tireoide e adrenal afastadas e sem diurético como causa. Causas: droga, pulmão, sistema nervoso, dor, náusea.",
    "Restrição hídrica é a primeira medida, em geral 800 a 1.000 mL por dia, no hospital se o sódio estiver baixo o bastante para sintoma. Soro fisiológico não é o tratamento do SIADH e pode piorar. Solução salina hipertônica só com sintoma neurológico grave, em ambiente monitorado. Não há vaptano nesta minuta.",
    ["Convulsão, rebaixamento: emergência"],
    ["Não corrigir sódio rápido", "Não prescrever soro fisiológico como receita de SIADH"],
    ["Diagnóstico de exclusão. Correção rápida causa desmielinização."],
    "alta",
    [R("siadh.hosp", "HOSPITAL", False, "Hiponatremia compatível com SIADH.",
       ["Internar se houver sintoma ou sódio muito baixo.",
        "Restringir líquido. Suspender a droga causadora.",
        "Não imprimir soro nem tolvaptano."],
       "Até o sódio estabilizar", "Sem receita de UBS", "A velocidade de correção é decisão do hospital.", "Nenhuma.", [], "alta")],
))

CONDICOES.append(C(
    "drc", "nefrologia", "Doença renal crônica", "N18",
    ["DRC", "rim crônico", "TFG baixa"],
    ["Sem sintoma até fases tardias", "Edema, náusea e prurido são tardios"],
    "TFG estimada pela CKD-EPI e relação albumina/creatinina, persistentes por mais de 3 meses. Estadiar G e A. Procurar causa.",
    "IECA ou BRA se houver albumina na urina e o potássio permitir. Pressão no alvo da diretriz de hipertensão. Suspender anti-inflamatório. Metformina conforme a TFG. Dapagliflozina se o PCDT de progressão da DRC for cumprido. Encaminhar ao nefrologista na G4, na queda rápida, no nefrótico ou na hematúria não explicada.",
    ["K alto, edema agudo, TFG em queda rápida"],
    ["Não associar IECA e BRA", "Não usar AINE"],
    ["PCDT de estratégias para atenuar a progressão da DRC, 2024, citado pela SBD", "Diretriz Brasileira de Hipertensão 2025"],
    "alta",
    [R("drc.ieca", "APS", True, "DRC com albumina na urina, K normal, não gestante, sem estenose bilateral.",
       ["Losartana potássica 50 mg: 1 comprimido pela manhã.",
        "Dosar creatinina e potássio em 1 a 2 semanas. Uma subida pequena da creatinina pode ser esperada. Subida grande ou K alto manda reduzir ou suspender.",
        "Parar anti-inflamatório."],
       "Contínuo", "30 comprimidos",
       "Se tosse, enalapril não é a troca: tosse é de IECA. Aqui o fármaco já é BRA.",
       "Dapagliflozina 10 mg só pelo PCDT, se idade e TFG ou albuminúria estiverem na regra.",
       ["losartana"], "alta")],
))

CONDICOES.append(C(
    "ira", "nefrologia", "Injúria renal aguda", "N17",
    ["IRA", "creatinina subiu", "rim agudo"],
    ["Queda da urina, edema, ou só o laboratório"],
    "KDIGO: creatinina sobe 0,3 mg/dL em 48 horas, ou 1,5 vez o basal em 7 dias, ou urina < 0,5 mL/kg/h por 6 horas. Separar pré-renal, renal e pós-renal. Ultrassom se houver suspeita de obstrução.",
    "Suspender AINE, IECA, BRA, diurético e metformina na doença aguda. Volume se estiver seco. Não usar dopamina. Não usar diurético para 'fazer o rim funcionar'. Obstrução infectada é urgência urológica.",
    ["K alto, edema de pulmão, anúria, sepse"],
    ["Não prescrever soro fixo sem examinar o volume", "Não repor potássio na oligúria"],
    ["KDIGO de injúria renal aguda"],
    "alta",
    [R("ira.parar", "APS", False, "Creatinina em alta, paciente ainda estável o bastante para investigar no mesmo dia.",
       ["Suspender anti-inflamatório, IECA ou BRA, espironolactona, diurético e metformina.",
        "Examinar volume e via urinária. Ultrassom se a causa não estiver clara.",
        "Se houver K alto, falta de ar ou anúria, hospital. Sem receita nova."],
       "Até definir a causa", "Sem receita", "Sem peso e sem exame de volume, não há soro nesta ficha.", "Nenhuma.", [], "alta")],
))

CONDICOES.append(C(
    "hipocalemia", "nefrologia", "Hipocalemia", "E87.6",
    ["potássio baixo", "hipocalemia"],
    ["Fraqueza, cãibra. Palpitação se grave."],
    "Dosar de novo se o valor for inesperado. ECG se houver sintoma ou K baixo. Procurar diurético, vômito, diarreia.",
    "Leve, sem alteração no ECG, com o paciente comendo e com rim funcionante: repor por boca e corrigir a causa. Grave, com ECG alterado ou íleo: hospital, reposição venosa monitorada. Não há número de comprimido aqui porque a apresentação de cloreto de potássio não foi confirmada nesta leitura da Rename.",
    ["Fraqueza ascendente, arritmia"],
    ["Não repor potássio na oligúria", "Não dar potássio venoso em bolus"],
    ["Reposição oral na hipocalemia leve sem alteração eletrocardiográfica"],
    "media",
    [R("k.leve", "APS", False, "K entre 3,0 e 3,4, ECG normal, come, urina preservada.",
       ["Suspender a causa se for diurético desnecessário.",
        "Repor cloreto de potássio por via oral na apresentação do município, em geral na faixa de 20 a 40 mEq por dia, fracionados, com comida.",
        "Nova dosagem em 48 a 72 horas. Se a apresentação local não estiver clara, não inventar o número de comprimidos."],
       "Dias", "Conforme a apresentação", "K abaixo de 3,0 ou ECG alterado não é esta ficha.", "Nenhuma.", [], "media")],
))

CONDICOES.append(C(
    "hipercalemia", "nefrologia", "Hipercalemia", "E87.5",
    ["potássio alto", "hipercalemia"],
    ["Pode não haver sintoma", "Fraqueza e arritmia quando grave"],
    "Repetir se a coleta hemolisou. ECG. Causas: IECA, BRA, espironolactona, AINE, DRC, suplemento.",
    "K acima de 6,0 ou qualquer alteração no ECG é hospital. Gluconato de cálcio, insulina com glicose e suspensão da causa são medidas de lá, não receita de casa. Resina não é tratamento de primeira linha.",
    ["Onda T apiculada, alargamento de QRS"],
    ["Não mandar para casa com K alto e ECG alterado", "Não usar soro com potássio"],
    ["Emergência eletrolítica"],
    "alta",
    [R("k.alto", "HOSPITAL", False, "Hipercalemia.",
       ["ECG. Se alterado ou K muito alto, hospital.",
        "Suspender IECA, BRA, espironolactona, AINE e suplemento.",
        "Sem receita de resina."],
       "Imediato", "Sem receita", "A dose de insulina e cálcio é do box de emergência, com monitor.", "Nenhuma.", [], "alta")],
))

CONDICOES.append(C(
    "hiponatremia", "nefrologia", "Hiponatremia", "E87.1",
    ["sódio baixo"],
    ["Náusea, confusão, queda"],
    "Medir osmolaridade, avaliar volume e sódio na urina antes de escolher o soro. Hipovolêmica, euvolêmica (ver SIADH) e hipervolêmica não recebem a mesma receita.",
    "Sintoma neurológico é hospital. Não existe uma ampola única.",
    ["Convulsão, rebaixamento"],
    ["Não corrigir rápido", "Não prescrever soro fisiológico sem classificar"],
    ["A classificação precede o soro"],
    "alta",
    [R("na.classificar", "HOSPITAL", False, "Sódio baixo.",
       ["Classificar o volume. Ver a ficha de SIADH se estiver euvolêmico.",
        "Sintoma neurológico: hospital. Sem receita pronta."],
       "Até classificar", "Sem receita", "Correção rápida lesa a mielina.", "Nenhuma.", [], "alta")],
))

CONDICOES.append(C(
    "gnm", "nefrologia", "Glomerulonefrite membranosa", "N04.2",
    ["membranosa", "síndrome nefrótica"],
    ["Edema, urina espumosa, proteinúria na faixa nefrótica"],
    "Proteinúria, albumina baixa, anti-PLA2R quando disponível, biópsia conforme o nefrologista. Afastar causa secundária, inclusive neoplasia no adulto.",
    "Suporte: pressão com IECA ou BRA, estatina se indicada, edema com diurético de alça. Imunossupressão (rituximabe ou ciclofosfamida) é decisão do nefrologista, não desta minuta. Risco de trombose sobe quando a albumina está muito baixa: anticoagular é decisão individual, não automática.",
    ["Trombose, anasarca, creatinina em subida"],
    ["Não prescrever ciclofosfamida na UBS", "Não anticoagular todo nefrótico por reflexo"],
    ["Conduta de suporte e encaminhamento. Imunossupressão fora desta minuta."],
    "alta",
    [R("gnm.suporte", "APS", True, "Diagnóstico já feito pelo nefrologista, estável, K normal.",
       ["Losartana potássica 50 mg: 1 comprimido pela manhã, se o potássio permitir.",
        "Furosemida 40 mg pela manhã se houver edema, com peso diário.",
        "Manter o retorno com o nefrologista. Sem imunossupressor nesta receita."],
       "Até a revisão do especialista", "30 comprimidos de losartana",
       "Dosar K e creatinina.",
       "Albumina muito baixa: discutir anticoagulação com quem acompanha, não iniciar varfarina sozinho nesta ficha.",
       ["losartana", "furosemida"], "media")],
))

CONDICOES.append(C(
    "uh", "nefrologia", "Ureterohidronefrose", "N13.3",
    ["hidronefrose", "rim inchado", "obstrução ureteral"],
    ["Dor lombar, queda da urina, febre se infectar"],
    "Ultrassom ou tomografia. Rim único, rim transplantado, creatinina em alta, dor incoercível ou febre com obstrução são urgência de descompressão.",
    "Descomprimir com cateter duplo J ou nefrostomia. Antibiótico não desobstrui. Se houver infecção, o antibiótico vem junto com a descompressão, no hospital.",
    ["Febre com obstrução, anúria, rim único"],
    ["Não tratar cólica obstrutiva infectada com comprimido"],
    ["Descompressão é o tratamento da obstrução complicada"],
    "alta",
    [R("uh.descomprimir", "HOSPITAL", False, "Hidronefrose obstrutiva.",
       ["Imagem e creatinina.",
        "Se infectada, rim único ou IRA: urologia no mesmo dia para duplo J ou nefrostomia.",
        "Analgesia com paracetamol enquanto encaminha, se não houver contraindicação. Sem antibiótico oral como tratamento."],
       "Até descomprimir", "Sem receita de antibiótico", "Cólica simples sem febre e com rim contralateral bom pode seguir o fluxo da urologia do serviço, ainda sem esta receita.", "Nenhuma.", ["paracetamol"], "alta")],
))

CONDICOES.append(C(
    "dialise", "nefrologia", "Critérios de diálise de urgência", "N18.5",
    ["diálise", "hemodiálise", "AEIOU"],
    ["Falta de ar por edema, pericardite, confusão, potássio incontrolável, acidose"],
    "Não há um valor de creatinina que, sozinho, indique diálise. Indicam urgência: acidose grave que não corrige, potássio alto refratário, intoxicação dialisável, sobrecarga que não responde, uremia com pericardite, encefalopatia ou sangramento.",
    "Encaminhar à nefrologia. Esta ficha é um lembrete, não uma receita.",
    ["Edema de pulmão, K com ECG alterado"],
    ["Não esperar um número mágico de ureia se houver pericardite ou edema refratário"],
    ["Mnemônico AEIOU, lido como decisão clínica e não como lista cega"],
    "alta",
    [R("dialise.lembrar", "HOSPITAL", False, "Dúvida de diálise urgente.",
       ["Acidose refratária, eletrólito (potássio) refratário, intoxicação dialisável, sobrecarga refratária, uremia com pericardite, encefalopatia ou sangramento.",
        "Creatinina isolada não basta. Acionar nefrologia."],
       "Imediato se um critério estiver presente", "Sem receita", "Diálise crônica programada é outro fluxo.", "Nenhuma.", [], "alta")],
))

CONDICOES.append(C(
    "derivacao", "nefrologia", "Derivação ureteral, resumo", "Z93.6",
    ["duplo J", "nefrostomia", "Bricker", "reimplante ureteral", "ureterostomia"],
    ["Urina por sonda, estoma ou flanco", "Febre e queda da urina significam obstrução ou infecção"],
    "Formas: cateter duplo J, nefrostomia, reimplante na bexiga, bexiga psoas-hitch, retalho de Boari, transuretero-ureterostomia, conduto ileal. O conduto ileal expõe a mucosa intestinal à urina e pode gerar acidose metabólica hiperclorêmica.",
    "Não há fármaco que substitua a via. Febre, anúria ou saída de urina pela ferida: imagem e urologia. Troca do duplo J no prazo combinado, em geral em meses, para não calcificar. Não introduzir antibiótico contínuo sem cultura e sem indicação.",
    ["Febre, flanco doloroso, anúria, acidose"],
    ["Não prescrever antibiótico profilático contínuo por hábito"],
    ["Resumo anatômico para a prescrição não atrasar a desobstrução"],
    "alta",
    [R("derivacao.resumo", "ENCAMINHAMENTO", False, "Pessoa com derivação urinária.",
       ["Perguntar qual via: J, nefrostomia ou estoma.",
        "Febre ou parada da urina: não é consulta eletiva.",
        "No conduto ileal, pensar em acidose se houver cansaço e hipercloremia.",
        "Sem antibiótico contínuo nesta minuta."],
       "Seguimento urológico", "Sem receita", "A data de troca do cateter tem de estar escrita.", "Nenhuma.", [], "alta")],
))

CONDICOES.append(C(
    "drge", "gastroenterologia", "Doença do refluxo", "K21",
    ["DRGE", "refluxo", "azia", "queimação"],
    ["Azia e regurgitação, piores ao deitar"],
    "Clínico. Endoscopia se houver alarme: disfagia, emagrecimento, anemia, vômito persistente, idade com sintoma novo.",
    "Medida de posição e comida. Omeprazol 20 mg pela manhã, em jejum, por 4 a 8 semanas. Curso finito. Não manter para sempre sem revisão.",
    ["Disfagia, emagrecimento, anemia, dor torácica"],
    ["Não renovar IBP por um ano sem reavaliar"],
    ["Rename 2024: omeprazol 20 mg cápsula no básico"],
    "alta",
    [R("drge.ibp", "APS", True, "Azia típica, sem alarme, adulto não gestante.",
       ["Omeprazol 20 mg: 1 cápsula pela manhã, em jejum, 30 minutos antes do café, por 4 semanas.",
        "Elevar a cabeceira. Não deitar nas 2 horas depois de comer.",
        "Se sumir, suspender. Se voltar ou não ceder, reavaliar antes de alongar até 8 semanas."],
       "4 semanas, no máximo 8", "28 cápsulas",
       "Alarme: endoscopia, não repetir a caixa.",
       "Omeprazol 10 mg se 20 mg der efeito adverso e o quadro for leve.",
       ["omeprazol"], "alta")],
))

CONDICOES.append(C(
    "hpylori", "gastroenterologia", "Helicobacter pylori", "K29.5",
    ["H. pylori", "úlcera", "dispepsia"],
    ["Dor epigástrica", "Pode ser achado de endoscopia"],
    "Testar e tratar quando houver indicação (úlcera, dispepsia não investigada conforme o fluxo local). Não tratar todo mundo com azia.",
    "Esquema concomitante por 14 dias, com os fármacos do básico: omeprazol, amoxicilina e, se o município tiver, claritromicina e metronidazol. A claritromicina não teve a linha confirmada nesta leitura da Rename. Por isso a receita imprimível usa o que está visto e manda conferir os outros dois antes de imprimir o quádruplo.",
    ["Hematemese, melena, peritonite: hospital"],
    ["Não usar esquema de 7 dias", "Não repetir claritromicina se já falhou"],
    ["Duração de 14 dias é o padrão atual dos esquemas. Rename 2024: omeprazol e amoxicilina no básico."],
    "media",
    [R("hp.conferir", "APS", False, "Indicação de erradicação já definida.",
       ["Não imprimir até confirmar no município: claritromicina 500 mg e metronidazol em comprimido.",
        "Esquema alvo, se os quatro existirem: omeprazol 20 mg de 12 em 12 horas, amoxicilina 1 g (dois comprimidos de 500 mg) de 12 em 12 horas, claritromicina 500 mg de 12 em 12 horas e metronidazol 400 ou 500 mg de 12 em 12 horas, todos por 14 dias.",
        "Sem claritromicina disponível, não inventar outro macrolídeo. Encaminhar ao fluxo local."],
       "14 dias", "Só imprimir quando as apresentações existirem",
       "Álcool proibido se houver metronidazol.",
       "Testar cura com teste respiratório ou antígeno fecal 4 semanas depois, fora de IBP.",
       ["omeprazol", "amoxicilina"], "media")],
))

CONDICOES.append(C(
    "diarreia", "gastroenterologia", "Diarreia aguda", "A09",
    ["diarreia", "gastroenterite"],
    ["Evacuações líquidas há menos de 14 dias"],
    "A maioria é viral e autolimitada. Antibiótico não é rotina. Sinais de invasão: sangue, febre alta, pus.",
    "Soro de reidratação oral. Comida habitual assim que tolerar. Antibiótico só no quadro disentérico grave ou no imunossuprimido, e mesmo assim conforme o protocolo, não nesta receita.",
    ["Sangue, prostração, incapacidade de beber, oligúria"],
    ["Não dar loperamida se houver sangue ou febre", "Não dar antibiótico para diarreia aquosa simples"],
    ["Reidratação é o tratamento"],
    "alta",
    [R("diarreia.sro", "APS", True, "Diarreia aquosa, sem sangue, consegue beber, adulto.",
       ["Sais de reidratação oral: preparar conforme o envelope e oferecer goles frequentes depois de cada evacuação.",
        "Comida habitual. Sem refrigerante.",
        "Retorno em 24 horas se não melhorar, ou antes se surgir sangue, febre ou incapacidade de beber."],
       "1 a 3 dias", "Envelopes de soro para 2 dias",
       "Não fixar um volume em litros sem ver idade, coração e rim.",
       "Sem antibiótico nesta ficha.",
       [], "alta")],
))

CONDICOES.append(C(
    "constipacao", "gastroenterologia", "Constipação", "K59.0",
    ["intestino preso", "constipação"],
    ["Esforço, fezes duras, menos de três evacuações por semana"],
    "Funcional depois de afastar alarme: sangue, anemia, emagrecimento, início depois dos 50 anos sem rastreamento.",
    "Fibra e água conforme o coração e o rim permitirem. Óleo mineral consta do básico, mas não é a melhor escolha crônica (aspiração, perda de vitaminas). Usar por curto prazo se for o que existe, nunca deitado.",
    ["Parada com vômito e distensão: obstrução", "Sangue"],
    ["Não usar óleo mineral deitado nem por meses"],
    ["Rename 2024: óleo mineral no básico"],
    "media",
    [R("constipa.oleo", "APS", True, "Constipação sem alarme, adulto que deglute bem, sem refluxo grave.",
       ["Óleo mineral: uma colher de sopa à noite, por no máximo 7 dias, sentado, nunca deitado.",
        "Aumentar fibra na comida.",
        "Se não resolver ou se houver alarme, investigar. Não renovar o óleo."],
       "Até 7 dias", "Frasco pequeno",
       "Risco de aspiração no idoso e em quem tem refluxo. Nesses, não usar.",
       "Se o município tiver polietilenoglicol, preferir. Não fixo dose porque não vi a apresentação.",
       [], "baixa")],
))

CONDICOES.append(C(
    "pancreatite", "gastroenterologia", "Pancreatite aguda", "K85",
    ["pancreatite"],
    ["Dor epigástrica em faixa, vômito"],
    "Dor mais lipase ou amilase em geral três vezes o limite. Causas frequentes: pedra e álcool. Gravidade pelo exame, não só pela enzima.",
    "Hospital. Hidratação com reavaliação, analgesia, comida oral cedo se tolerar. Antibiótico não é rotina. Necrose infectada é outra conversa, tardia, com imagem.",
    ["Hipotensão, falta de ar, oligúria"],
    ["Não dar antibiótico no primeiro dia sem infecção", "Não deixar em jejum prolongado se estiver melhorando"],
    ["Antibiótico profilático não melhora a pancreatite intersticial"],
    "alta",
    [R("panc.hosp", "HOSPITAL", False, "Pancreatite aguda.",
       ["Encaminhar. Analgesia no caminho conforme o serviço.",
        "Sem antibiótico de rotina.",
        "A causa biliar pode precisar de CPRE se houver colangite associada."],
       "Hospitalar", "Sem receita", "Jejum longo piora.", "Nenhuma.", [], "alta")],
))

CONDICOES.append(C(
    "hda", "gastroenterologia", "Hemorragia digestiva alta", "K92.2",
    ["hematêmese", "melena", "vômito com sangue"],
    ["Vômito de sangue ou borra de café, fezes negras, tontura"],
    "É emergência. Estabilidade, acesso, tipagem. IBP venoso e endoscopia são do hospital. Não há receita de cápsula para casa no sangramento ativo.",
    "SAMU ou urgência. Suspender anti-inflamatório e anticoagulante até a avaliação, registrando o que foi suspenso.",
    ["Hipotensão, síncope, hematêmese volumosa"],
    ["Não dar omeprazol em casa e dispensar"],
    ["Via de sangramento alto é hospitalar"],
    "alta",
    [R("hda.samu", "EMERGENCIA", False, "Sangramento digestivo.",
       ["Acionar urgência. Jejum.",
        "Anotar AAS, varfarina, anti-inflamatório.",
        "Sem receita."],
       "Imediato", "Sem receita", "INR se usar varfarina, no hospital.", "Nenhuma.", [], "alta")],
))

CONDICOES.append(C(
    "asma", "pneumologia", "Asma", "J45",
    ["asma", "chiado", "falta de ar"],
    ["Chiado, aperto, tosse, piora à noite ou com esforço"],
    "Clínico. Crise grave com fala entrecortada e saturação baixa é urgência. O tratamento de fundo é corticoide inalatório, não só a bombinha de resgate.",
    "Resgate com salbutamol. Manutenção com o corticoide inalatório que o município dispensa. Não fixo microgramas porque não reli o frasco na Rename nesta sessão. Corticoide oral não é tratamento de fundo.",
    ["Fala entrecortada, saturação baixa, silêncio auscultatório"],
    ["Não tratar asma só com salbutamol todo dia", "Não manter prednisona como controlador"],
    ["GINA: corticoide inalatório é a base. Apresentação local a conferir."],
    "media",
    [R("asma.resgate", "APS", True, "Asma estável no momento da consulta, saturação boa.",
       ["Sulfato de salbutamol aerossol, na apresentação do município: 2 jatos se faltar o ar, podendo repetir uma vez. Se não aliviar, urgência.",
        "Corticoide inalatório do componente básico, todo dia, na dose da apresentação local. Não deixo microgramas inventados.",
        "Ensinar a técnica. Espaçador se houver."],
       "Controlador contínuo; resgate se preciso", "Conforme o frasco",
       "Crise grave não sai com esta receita: nebulização e avaliação imediata.",
       "Se não houver corticoide inalatório na farmácia, registrar a falta. Não substituir por prednisona contínua.",
       ["salbutamol"], "baixa")],
))

CONDICOES.append(C(
    "dpoc", "pneumologia", "Exacerbação da DPOC", "J44.1",
    ["DPOC", "enfisema", "bronquite crônica"],
    ["Falta de ar acima do habitual, mais escarro ou escarro purulento, em quem fuma ou fumou"],
    "Separar exacerbação de pneumonia e de insuficiência cardíaca. Gravidade pela fala, saturação e esforço.",
    "Salbutamol de resgate. Prednisona ou prednisolona 40 mg pela manhã por 5 dias, sem desmame, se a apresentação existir. Antibiótico só se houver aumento da purulência do escarro, além da dispneia. Amoxicilina é o Access.",
    ["Saturação baixa, confusão, cianose"],
    ["Não alongar corticoide", "Não dar antibiótico em todo chiado"],
    ["GOLD: corticoide oral por 5 dias na exacerbação. Rename: amoxicilina 500 mg."],
    "media",
    [R("dpoc.exac", "APS", True, "Exacerbação leve, fala frases, saturação estável, come, sem pneumonia.",
       ["Sulfato de salbutamol: 2 jatos de 4 em 4 horas se precisar, na apresentação local.",
        "Prednisona ou prednisolona 40 mg: 1 dose pela manhã por 5 dias, se o comprimido do município fechar essa dose. Sem desmame.",
        "Se o escarro ficou purulento e a dispneia aumentou: amoxicilina 500 mg, 1 comprimido de 8 em 8 horas, por 5 dias.",
        "Se piorar, urgência."],
       "5 dias", "Amoxicilina: 15 comprimidos, só se a linha do escarro for usada",
       "Confirmar o mg do corticoide antes de imprimir. Não escrever 40 mg se o comprimido for outro.",
       "Sem purulência, não incluir a amoxicilina.",
       ["salbutamol", "prednisona", "amoxicilina"], "media")],
))

CONDICOES.append(C(
    "enxaqueca", "neurologia", "Enxaqueca", "G43",
    ["enxaqueca", "migrânea", "dor de cabeça latejante"],
    ["Dor latejante, náusea, foto e fonofobia, piora com esforço"],
    "Clínico. Alarme: início súbito máximo, déficit, febre com rigidez, depois dos 50 anos como dor nova, piora progressiva, imunossupressão.",
    "Crise: ibuprofeno 600 mg, que está no básico, cedo na dor. Teto e contraindicações do AINE. Profilaxia não entra com valproato em mulher que pode engravidar. Propranolol não teve a linha confirmada nesta leitura, então não há receita de profilaxia imprimível.",
    ["Déficit, trovão, febre com rigidez"],
    ["Não usar opioide", "Não usar valproato para enxaqueca em mulher com útero"],
    ["Rename 2024: ibuprofeno 600 mg no básico. Valproato é teratogênico."],
    "alta",
    [R("enx.crise", "APS", True, "Crise típica, sem alarme, sem úlcera, sem DRC, sem gestação, sem insuficiência cardíaca.",
       ["Ibuprofeno 600 mg: 1 comprimido no início da dor. Pode repetir uma vez após 8 horas se precisar.",
        "Máximo 1200 mg no dia nesta minuta.",
        "Se as crises passarem de 4 por mês, marcar retorno para profilaxia. Sem valproato."],
       "Sintomático", "10 comprimidos, para não virar uso diário",
       "Mais de 10 dias de analgésico por mês piora a dor. Avisar.",
       "Paracetamol 500 mg, 1 a 2 comprimidos, se o AINE for contraindicado. Teto 3 g no dia.",
       ["ibuprofeno"], "alta")],
))

CONDICOES.append(C(
    "avc", "neurologia", "Acidente vascular cerebral isquêmico", "I63",
    ["AVC", "derrame", "déficit súbito"],
    ["Face torta, braço fraco, fala enrolada, de instalação súbita"],
    "Tempo de início. Hospital com tomografia. AAS só depois de excluir hemorragia. Esta ficha não trombolisa e não leva AAS para casa na hora H.",
    "SAMU. Não baixar a pressão na UBS. Não dar AAS antes da imagem.",
    ["Rebaixamento, convulsão"],
    ["Não dar AAS antes da tomografia", "Não reter para 'ver se passa'"],
    ["Janela de reperfusão. Hemorragia precisa ser excluída."],
    "alta",
    [R("avc.samu", "EMERGENCIA", False, "Déficit súbito.",
       ["Anotar a hora em que começou, ou a última vez em que estava normal.",
        "SAMU. Sem AAS, sem anti-hipertensivo e sem receita."],
       "Imediato", "Sem receita", "AAS de prevenção secundária é conversa de depois da alta, com imagem já feita.", "Nenhuma.", [], "alta")],
))

CONDICOES.append(C(
    "vertigem", "neurologia", "Vertigem periférica", "H81",
    ["vertigem", "labirintite", "tontura rotatória"],
    ["Giro, náusea, piora com a cabeça, sem déficit"],
    "Periférica: giro intenso, nistagmo horizontal que cansa, sem déficit. Central: déficit, ataxia, cefaleia nova, nistagmo vertical. Dix-Hallpike sugere canal posterior.",
    "Manobra de reposicionamento quando o exame for típico. Sintomático por poucos dias. Clonazepam não é tratamento. Não fixo dimenidrinato porque não vi a apresentação.",
    ["Déficit, disartria, diplopia, cefaleia em trovão"],
    ["Não prescrever benzodiazepínico para labirintite", "Não chamar de labirintite o que é central"],
    ["Manobra é o tratamento da vertigem posicional paroxística benigna"],
    "alta",
    [R("vertigem.manobra", "APS", False, "Giro posicional, sem déficit, exame compatível com canal posterior.",
       ["Fazer a manobra de reposicionamento se o examinador souber.",
        "Avisar que a tontura pode intensificar durante a manobra.",
        "Sem clonazepam. Se precisar de anti-histamínico, usar só por 2 ou 3 dias e só a apresentação que o município tiver, sem dose inventada.",
        "Déficit: esta ficha não serve. Ver AVC."],
       "Manobra no dia", "Sem receita de benzodiazepínico", "Sintoma que não cede ou exame atípico: reavaliar como central.", "Nenhuma.", [], "alta")],
))

CONDICOES.append(C(
    "delirium", "neurologia", "Delirium e agitação", "F05",
    ["delirium", "confusão aguda", "agitação"],
    ["Início em horas ou dias, atenção flutuante, pensamento desorganizado"],
    "Não é doença psiquiátrica primária até afastar infecção, dor, retenção, hipóxia, hipoglicemia, droga e abstinência. Neuroléptico não trata a causa.",
    "Tratar a causa. Ambiente, acompanhante, sono, retirar contenção química. Haloperidol, clorpromazina e risperidona não têm receita de balcão nesta minuta. Se a segurança exigir antipsicótico, é no hospital, com ECG e dose baixa, por quem está presente.",
    ["Hipoglicemia, hipóxia, abstinência de álcool com convulsão"],
    ["Não prescrever neuroléptico para insônia", "Não amarrar a conduta num comprimido sem procurar a causa"],
    ["Neurolépticos constam como categoria. Apresentação não fixada nesta leitura da Rename."],
    "alta",
    [R("delirium.causa", "HOSPITAL", False, "Confusão aguda.",
       ["Glicemia, saturação, exame, retenção urinária, fármacos novos.",
        "Sem receita de haloperidol, clorpromazina ou risperidona.",
        "Abstinência de álcool com agitação é outro protocolo, com benzodiazepínico monitorado, não esta ficha."],
       "Até achar a causa", "Sem receita", "QTc e queda contraindicam a pressa do neuroléptico.", "Nenhuma.", [], "alta")],
))
