# -*- coding: utf-8 -*-
"""Elenco lido na Rename 2024 (trechos oficiais) ou marcado para conferir no painel."""

FARMACOS = [
    # --- anti-hipertensivos e afins ---
    dict(id="losartana", nome="losartana potássica", categoria="anti-hipertensivo", classe="BRA",
         apresentacoes=["50 mg comprimido"], componente="basico", fonte="Rename 2024",
         ajuste="reduzir ou evitar se potássio alto ou TFG muito baixa; não associar a IECA",
         gestacao="contraindicada", alerta="não combinar com IECA nem com suplemento de potássio sem dosar K"),
    dict(id="enalapril", nome="maleato de enalapril", categoria="anti-hipertensivo", classe="IECA",
         apresentacoes=["5 mg", "10 mg", "20 mg comprimido"], componente="basico_habitual",
         fonte="elenco espelhado da Rename; confirmar linha no painel 2024",
         ajuste="iniciar mais baixo se PA baixa, idoso ou depleção; suspender se K alto ou creatinina em alta",
         gestacao="contraindicada", alerta="tosse; angioedema; não associar a BRA"),
    dict(id="captopril", nome="captopril", categoria="anti-hipertensivo", classe="IECA",
         apresentacoes=["25 mg comprimido"], componente="basico", fonte="Rename 2024",
         ajuste="dose fracionada; ajustar na DRC", gestacao="contraindicada",
         alerta="efeito mais curto que o enalapril; útil quando se quer titular em horas"),
    dict(id="anlodipino", nome="besilato de anlodipino", categoria="anti-hipertensivo", classe="BCC",
         apresentacoes=["5 mg", "10 mg comprimido"], componente="basico", fonte="Rename 2024",
         ajuste="sem ajuste renal obrigatório", gestacao="evitar se houver alternativa com mais dados",
         alerta="edema maleolar; não tratar esse edema com diurético como primeira medida"),
    dict(id="hctz", nome="hidroclorotiazida", categoria="diurético", classe="tiazídico",
         apresentacoes=["12,5 mg", "25 mg comprimido"], componente="basico", fonte="Rename 2024",
         ajuste="evitar se TFG muito baixa, o tiazídico perde efeito; vigiar sódio e potássio",
         gestacao="não é escolha", alerta="hiponatremia no idoso; piora glicemia e ácido úrico"),
    dict(id="atenolol", nome="atenolol", categoria="betabloqueador", classe="beta-1 seletivo",
         apresentacoes=["50 mg", "100 mg comprimido"], componente="basico", fonte="Rename 2024",
         ajuste="reduzir na DRC", gestacao="pode ser usado com monitorização quando indicado",
         alerta="não é betabloqueador de escolha na ICFEr"),
    dict(id="carvedilol", nome="carvedilol", categoria="betabloqueador", classe="alfa-beta",
         apresentacoes=["3,125 mg", "6,25 mg", "12,5 mg", "25 mg comprimido"], componente="basico",
         fonte="Rename 2024", ajuste="não iniciar em congestão aguda", gestacao="avaliar caso a caso",
         alerta="dose alvo na ICFEr: 25 mg 12/12 h se peso < 85 kg; 50 mg 12/12 h se peso ≥ 85 kg"),
    dict(id="metoprolol_succinato", nome="succinato de metoprolol", categoria="betabloqueador",
         classe="beta-1 seletivo de liberação prolongada",
         apresentacoes=["25 mg", "50 mg", "100 mg comprimido de liberação prolongada"],
         componente="conferir_painel", fonte="elenco municipal espelhando a Rename; confirmar 2024",
         ajuste="não partir o comprimido de liberação prolongada salvo orientação da bula da marca",
         gestacao="avaliar caso a caso", alerta="é uma das opções com evidência na ICFEr; o tartarato não substitui o succinato nessa indicação"),
    dict(id="espironolactona", nome="espironolactona", categoria="diurético", classe="antagonista mineralocorticoide",
         apresentacoes=["25 mg comprimido"], componente="basico", fonte="Rename 2024",
         ajuste="não iniciar se K > 5,0 mmol/L ou creatinina muito elevada; dosar K e creatinina em 1 semana e em 4 semanas",
         gestacao="evitar", alerta="ginecomastia; hipercalemia, sobretudo com IECA ou BRA"),
    dict(id="furosemida", nome="furosemida", categoria="diurético", classe="alça",
         apresentacoes=["40 mg comprimido", "10 mg/mL solução injetável"], componente="basico_habitual",
         fonte="Rename 2020 explicita o básico; confirmar linha 2024",
         ajuste="só para congestão; não é anti-hipertensivo de rotina", gestacao="pode ser necessária na congestão",
         alerta="hipocalemia e lesão renal se usada sem congestão"),
    dict(id="doxazosina", nome="mesilato de doxazosina", categoria="anti-hipertensivo", classe="alfabloqueador",
         apresentacoes=["2 mg", "4 mg comprimido"], componente="conferir_painel",
         fonte="trecho de elenco municipal", ajuste="hipotensão de primeira dose",
         gestacao="evitar", alerta="não é classe preferencial da HAS; queda no idoso"),
    # --- dislipidemia, antiagregante, anticoagulação, angina ---
    dict(id="sinvastatina", nome="sinvastatina", categoria="hipolipemiante", classe="estatina",
         apresentacoes=["10 mg", "20 mg", "40 mg comprimido"], componente="basico_habitual",
         fonte="elenco do componente básico; confirmar painel 2024",
         ajuste="evitar 80 mg; não associar a fibrato sem necessidade", gestacao="contraindicada",
         alerta="tomar à noite; miopatia; a alta intensidade (atorvastatina 40–80 mg) está no componente especializado, não no básico"),
    dict(id="atorvastatina", nome="atorvastatina cálcica", categoria="hipolipemiante", classe="estatina de alta intensidade",
         apresentacoes=["10 mg", "20 mg", "40 mg", "80 mg comprimido"], componente="especializado",
         fonte="Rename 2024", ajuste="conforme PCDT e critério de acesso", gestacao="contraindicada",
         alerta="não imprimir como item do componente básico"),
    dict(id="aas", nome="ácido acetilsalicílico", categoria="antiagregante", classe="antiagregante",
         apresentacoes=["500 mg comprimido (trecho analgésico da Rename 2024)"], componente="basico",
         fonte="Rename 2024 explicita 500 mg; a apresentação de 100 mg precisa ser confirmada no município",
         ajuste="evitar se sangramento ativo, úlcera ou alergia", gestacao="não usar no terceiro trimestre como rotina",
         alerta="não prescrever 500 mg por dia como prevenção cardiovascular"),
    dict(id="varfarina", nome="varfarina sódica", categoria="anticoagulante", classe="antivitamina K",
         apresentacoes=["1 mg", "5 mg comprimido"], componente="basico", fonte="Rename 2024",
         ajuste="INR alvo em geral 2,0–3,0 na FA não valvar; interações com antibióticos, amiodarona e dieta",
         gestacao="contraindicada; teratogênica", alerta="não iniciar sem plano de INR e serviço que acompanhe"),
    dict(id="isossorbida", nome="dinitrato de isossorbida", categoria="antianginoso", classe="nitrato",
         apresentacoes=["5 mg comprimido sublingual"], componente="basico", fonte="Rename 2024",
         ajuste="sentar antes de usar", gestacao="evitar hipotensão",
         alerta="dor que não cede é emergência; não substitui o SAMU"),
    # --- diabetes ---
    dict(id="metformina", nome="cloridrato de metformina", categoria="antidiabético", classe="biguanida",
         apresentacoes=["500 mg", "850 mg comprimido"], componente="basico",
         fonte="SBD 2026 citando Rename e PCDT do DM2",
         ajuste="máximo 1000 mg/dia se TFG < 45; suspender se TFG < 30",
         gestacao="a insulina é o tratamento da hiperglicemia na gestação",
         alerta="suspender em doença aguda com risco de desidratação, contraste iodado e acidose"),
    dict(id="glibenclamida", nome="glibenclamida", categoria="antidiabético", classe="sulfonilureia",
         apresentacoes=["5 mg comprimido"], componente="basico", fonte="SBD 2026 / PCDT DM2",
         ajuste="evitar no idoso e na DRC pelo risco de hipoglicemia prolongada",
         gestacao="não usar", alerta="a SBD prefere gliclazida quando houver sulfonilureia"),
    dict(id="gliclazida", nome="gliclazida", categoria="antidiabético", classe="sulfonilureia",
         apresentacoes=["30 mg", "60 mg comprimido"], componente="basico", fonte="SBD 2026 / PCDT DM2",
         ajuste="hipoglicemia menor que a da glibenclamida, mas existe; cuidado na DRC avançada",
         gestacao="não usar", alerta="faixa citada pela SBD 2024: 30 a 120 mg/dia"),
    dict(id="dapagliflozina", nome="dapagliflozina", categoria="antidiabético", classe="iSGLT2",
         apresentacoes=["10 mg comprimido"], componente="especializado",
         fonte="SBD 2026; PCDT de ICFEr; PCDT de progressão da DRC (Portaria Conjunta SAES/SECTICS 11/2024)",
         ajuste="não iniciar se TFG muito baixa conforme o PCDT da indicação; suspender em doença aguda",
         gestacao="contraindicada", alerta="infecção genital; cetoacidose euglicêmica; não é item livre do básico"),
    dict(id="insulina_nph", nome="insulina humana NPH", categoria="insulina", classe="insulina basal",
         apresentacoes=["100 UI/mL frasco 10 mL ou tubete"], componente="basico", fonte="SBD 2026 / Rename",
         ajuste="início noturno 10 UI ou 0,2 UI/kg; titular 2 a 4 UI pela glicemia de jejum",
         gestacao="pode ser usada", alerta="hipoglicemia noturna; orientar glucagem e sinais"),
    dict(id="insulina_regular", nome="insulina humana regular", categoria="insulina", classe="insulina prandial",
         apresentacoes=["100 UI/mL"], componente="basico", fonte="SBD 2026 / Rename",
         ajuste="associar quando a NPH otimizada não cobre o pós-prandial",
         gestacao="pode ser usada", alerta="aplicar antes da refeição; não misturar no mesmo cálculo sem esquema escrito"),
    # --- tireoide, osso ---
    dict(id="levotiroxina", nome="levotiroxina sódica", categoria="hormônio tireoidiano", classe="T4",
         apresentacoes=["12,5 mcg", "25 mcg", "37,5 mcg", "50 mcg", "100 mcg comprimido"],
         componente="basico_habitual", fonte="elenco do componente básico; confirmar painel 2024",
         ajuste="jejum, 30–60 min antes do café; separar de cálcio, ferro e IBP em 4 h",
         gestacao="aumentar a necessidade; não suspender", alerta="no idoso ou com coronariopatia começar com 12,5–25 mcg"),
    dict(id="alendronato", nome="alendronato de sódio", categoria="antirreabsortivo", classe="bisfosfonato",
         apresentacoes=["10 mg", "70 mg comprimido"], componente="basico", fonte="Rename 2024",
         ajuste="não usar se TFG < 35; jejum com água, permanecer em pé 30 min",
         gestacao="contraindicado", alerta="corrigir cálcio e vitamina D antes; avaliar boca"),
    # --- gastro e sintomáticos vistos ---
    dict(id="omeprazol", nome="omeprazol", categoria="supressor ácido", classe="IBP",
         apresentacoes=["10 mg", "20 mg cápsula"], componente="basico", fonte="Rename 2024",
         ajuste="curso finito na DRGE não complicada", gestacao="usar só se o benefício for claro",
         alerta="não manter contínuo sem revisão; reduz absorção de ferro, B12 e magnésio no uso longo"),
    dict(id="ibuprofeno", nome="ibuprofeno", categoria="analgésico", classe="AINE",
         apresentacoes=["200 mg", "300 mg", "600 mg", "50 mg/mL suspensão"], componente="basico",
         fonte="Rename 2024", ajuste="evitar na DRC, IC, úlcera e no terceiro trimestre",
         gestacao="evitar, sobretudo no terceiro trimestre", alerta="não usar como anti-hipertensivo de dor crônica"),
    dict(id="paracetamol", nome="paracetamol", categoria="analgésico", classe="analgésico antipirético",
         apresentacoes=["500 mg comprimido", "200 mg/mL solução oral"], componente="basico",
         fonte="Rename 2024", ajuste="teto habitual 3 g/dia no adulto com fígado são; menos se hepatopatia ou baixo peso",
         gestacao="é o analgésico preferido quando preciso", alerta="não somar com outros produtos que já contenham paracetamol"),
    # --- antibióticos. AWaRe da OMS, adotada pela Rename 2024 ---
    dict(id="amoxicilina", nome="amoxicilina", categoria="antibiótico", classe="betalactâmico", aware="Access",
         apresentacoes=["500 mg cápsula ou comprimido", "50 mg/mL suspensão"], componente="basico",
         fonte="Anexo da Rename 2024", ajuste="alongar intervalo na TFG baixa",
         gestacao="compatível quando indicada", alerta="alergia a penicilina"),
    dict(id="amox_clav", nome="amoxicilina + clavulanato", categoria="antibiótico", classe="betalactâmico",
         aware="Access", apresentacoes=["500 mg + 125 mg comprimido", "50 mg/mL + 12,5 mg/mL suspensão"],
         componente="basico", fonte="Anexo da Rename 2024",
         ajuste="a apresentação vista é 500/125, de 8/8 h; não escrever 875/125 se o município não tiver",
         gestacao="compatível quando indicada", alerta="diarreia; hepatotoxicidade do clavulanato"),
    dict(id="cefalexina", nome="cefalexina", categoria="antibiótico", classe="cefalosporina de 1ª geração",
         aware="Access", apresentacoes=["500 mg cápsula ou comprimido", "50 mg/mL suspensão"],
         componente="basico", fonte="Anexo da Rename 2024", ajuste="alongar intervalo na TFG baixa",
         gestacao="compatível quando indicada", alerta="alergia cruzada é incomum, mas existe se a reação à penicilina foi grave"),
    dict(id="azitromicina", nome="azitromicina", categoria="antibiótico", classe="macrolídeo", aware="Watch",
         apresentacoes=["500 mg comprimido", "40 mg/mL pó para suspensão"], componente="basico",
         fonte="Anexo da Rename 2024", ajuste="cuidado com QTc", gestacao="avaliar caso a caso",
         alerta="Watch: não usar como atalho para toda infecção respiratória"),
    dict(id="ceftriaxona", nome="ceftriaxona", categoria="antibiótico", classe="cefalosporina de 3ª geração",
         aware="Watch", apresentacoes=["250 mg", "500 mg", "1 g pó para solução injetável"],
         componente="hospitalar_ou_urgencia", fonte="Anexo da Rename 2024",
         ajuste="não é tratamento de UBS para levar para casa", gestacao="pode ser usada quando indicada",
         alerta="2 g exigem dois frascos de 1 g"),
    dict(id="metronidazol", nome="metronidazol", categoria="antibiótico", classe="nitroimidazólico", aware="Access",
         apresentacoes=["benzoilmetronidazol 40 mg/mL suspensão consta do anexo; comprimido de 250 ou 400 mg conferir"],
         componente="conferir_painel", fonte="suspensão vista na Rename 2024; comprimido a conferir",
         ajuste="não usar com álcool", gestacao="evitar no primeiro trimestre se houver alternativa",
         alerta="não tratar fístula como vaginite"),
    dict(id="ciprofloxacino", nome="ciprofloxacino", categoria="antibiótico", classe="fluoroquinolona", aware="Watch",
         apresentacoes=["250 mg e outras; conferir"], componente="conferir_painel", fonte="linha iniciada no anexo 2024",
         ajuste="evitar se houver betalactâmico adequado; tendão, QTc, aneurisma, miastenia",
         gestacao="evitar", alerta="não é primeira linha de diverticulite nem de pneumonia"),
    dict(id="nitrofurantoina", nome="nitrofurantoína", categoria="antibiótico", classe="nitrofurano", aware="Access",
         apresentacoes=["100 mg cápsula", "5 mg/mL suspensão"], componente="basico_habitual",
         fonte="elenco 2024 de secretaria municipal espelhando a Rename",
         ajuste="não usar se TFG < 30–45 nem para pielonefrite", gestacao="evitar no termo e no trabalho de parto",
         alerta="só para cistite baixa"),
    dict(id="penicilina_benzatina", nome="benzilpenicilina benzatina", categoria="antibiótico",
         classe="penicilina de depósito", aware="Access",
         apresentacoes=["600.000 UI", "1.200.000 UI"], componente="basico_habitual",
         fonte="anexo da Rename 2024", ajuste="só intramuscular; nunca intravenosa",
         gestacao="tratamento de sífilis", alerta="não entra nas receitas deste compêndio"),
    # --- respiratório: apresentação não relida nesta sessão ---
    dict(id="salbutamol", nome="sulfato de salbutamol", categoria="broncodilatador", classe="beta-2 agonista",
         apresentacoes=["aerossol; confirmar microgramas do frasco"], componente="conferir_painel",
         fonte="uso padrão no SUS; apresentação não relida nesta sessão",
         ajuste="resgate, não manutenção isolada da asma", gestacao="pode ser usado",
         alerta="tremor e taquicardia"),
    dict(id="prednisona", nome="prednisona ou prednisolona", categoria="corticoide", classe="corticoide sistêmico",
         apresentacoes=["confirmar mg do comprimido dispensado"], componente="conferir_painel",
         fonte="curso curto de exacerbação da DPOC é recomendação GOLD; apresentação local a conferir",
         ajuste="curso de 5 dias não exige desmame", gestacao="curso curto quando a exacerbação o exige",
         alerta="não manter corticoide oral como tratamento de fundo da asma ou da DPOC"),
    # --- sistema nervoso visto na Rename ---
    dict(id="carbamazepina", nome="carbamazepina", categoria="anticonvulsivante", classe="bloqueador de canal de sódio",
         apresentacoes=["200 mg", "400 mg comprimido", "20 mg/mL suspensão"], componente="basico",
         fonte="Rename 2024", ajuste="induz metabolização de varfarina e anticoncepcional",
         gestacao="risco teratogênico; não iniciar sem neurologia", alerta="hiponatremia, Steven-Johnson, HLA em populações de risco"),
    dict(id="valproato", nome="valproato de sódio ou ácido valproico", categoria="anticonvulsivante",
         classe="amplo espectro", apresentacoes=["250 mg", "300 mg", "500 mg", "50 mg/mL"],
         componente="basico", fonte="Rename 2024", ajuste="hepatotoxicidade; não usar em hepatopatia",
         gestacao="contraindicado em mulher com potencial de engravidar para enxaqueca e, na epilepsia, só sem alternativa",
         alerta="não prescrever para dor nem para humor nesta minuta"),
    dict(id="litio", nome="carbonato de lítio", categoria="estabilizador de humor", classe="lítio",
         apresentacoes=["300 mg comprimido"], componente="basico", fonte="Rename 2024",
         ajuste="faixa sérica estreita; DRC, IECA, diurético e AINE elevam o nível",
         gestacao="teratogênico", alerta="não é neuroléptico e não entra em receita de insônia"),
    dict(id="clonazepam", nome="clonazepam", categoria="benzodiazepínico", classe="benzodiazepínico",
         apresentacoes=["2,5 mg/mL solução oral"], componente="basico", fonte="Rename 2024",
         ajuste="queda no idoso; depressão respiratória", gestacao="evitar",
         alerta="controle especial; não usar como tratamento de vertigem nem de insônia crônica"),
    dict(id="haloperidol", nome="haloperidol", categoria="neuroléptico", classe="antipsicótico típico",
         apresentacoes=["confirmar no painel"], componente="conferir_painel",
         fonte="não fixei apresentação nesta leitura", ajuste="QTc, extrapiramidal, queda",
         gestacao="evitar", alerta="sem receita de balcão; não usar para insônia"),
    dict(id="clorpromazina", nome="clorpromazina", categoria="neuroléptico", classe="antipsicótico típico",
         apresentacoes=["confirmar no painel"], componente="conferir_painel",
         fonte="não fixei apresentação nesta leitura", ajuste="hipotensão, sedação, QTc",
         gestacao="evitar", alerta="sem receita de balcão"),
    dict(id="risperidona", nome="risperidona", categoria="neuroléptico", classe="antipsicótico atípico",
         apresentacoes=["confirmar componente, em geral especializado"], componente="conferir_painel",
         fonte="não fixei linha nesta leitura", ajuste="dose baixa no idoso; AVC em demência",
         gestacao="evitar", alerta="não prescrever para agitacão não especificada"),
]
