import { describe,it,expect } from 'vitest';
import { changeWorkspace,initialWorkspace,matchWorkspace } from '../../../src/app/estudio/workspace.js';
const now='2026-10-05T15:00:00-03:00';
const command=(action:string,rest:Record<string,string>={})=>new URLSearchParams({action,...rest});
const source=JSON.stringify({title:'Estudo fictício',description:'Somente teste',arms:[{id:'a',name:'Braço fictício A'},{id:'b',name:'Braço fictício B'}],inclusionCriteria:['Marcador de teste presente.'],exclusionCriteria:['Impedimento de teste presente.'],outcomes:['Desfecho fictício.']});
async function setup(){let w=await changeWorkspace(initialWorkspace(),command('study-import',{fileName:'estudo.json',mime:'application/json',content:source}),'medico-teste',now);const s=w.studies[0]!;const bind:Record<string,string>={confirm:'sim'};for(const c of [...s.candidate.inclusionCriteria,...s.candidate.exclusionCriteria]){bind['op:'+c.criterionId]='EQUALS';bind['key:'+c.criterionId]=c.polarity==='INCLUSAO'?'marcador':'impedimento';bind['value:'+c.criterionId]='presente';}w=await changeWorkspace(w,command('study-review',bind),'medico-teste',now);return w;}
describe('workspace local de pesquisa',()=>{
 it('importa, revisa, cruza somente fatos confirmados e não declara elegibilidade',async()=>{let w=await setup();expect(matchWorkspace(w,'2026-10-05')?.status).toBe('PENDENTE');for(const [key,value] of [['marcador','presente'],['impedimento','ausente']])w=await changeWorkspace(w,command('patient-fact',{confirm:'sim',factKey:key!,factValue:value!,factSource:'registro médico de teste',factDate:'2026-10-05'}),'medico-teste',now);expect(matchWorkspace(w,'2026-10-05')?.status).toBe('POSSIBLE_MATCH');expect(w.patients[0]!.facts[0]!.status).toBe('CONFIRMADO');});
 it('preserva divergência sem sobrescrever e não aceita dado de outro paciente',async()=>{let w=await setup();for(const v of ['presente','ausente'])w=await changeWorkspace(w,command('patient-fact',{confirm:'sim',factKey:'marcador',factValue:v,factSource:'fonte '+v,factDate:'2026-10-05'}),'medico-teste',now);expect(w.patients[0]!.facts).toHaveLength(2);expect(matchWorkspace(w,'2026-10-05')?.status).toBe('PENDENTE');w=await changeWorkspace(w,command('patient-add',{confirm:'sim',nome:'Paciente Teste 002',fase:'EM_TRATAMENTO'}),'medico-teste',now);expect(matchWorkspace(w,'2026-10-05')?.criteria.every(c=>c.status==='PENDENTE')).toBe(true);});
 it('recusa alocação divergente na mesma data e evento sem vínculo',async()=>{let w=await setup();const event=command('followup',{confirm:'sim',armId:'a',kind:'IMAGING',eventDate:'2026-10-05',eventSource:'laudo sintético',description:'Achado indeterminado, sem comparação prévia.',modality:'TC'});await expect(changeWorkspace(w,event,'medico-teste',now)).rejects.toThrow();w=await changeWorkspace(w,command('enroll',{confirm:'sim',armId:'a',assignmentDate:'2026-10-05',assignmentSource:'documento fictício'}),'medico-teste',now);await expect(changeWorkspace(w,command('enroll',{confirm:'sim',armId:'b',assignmentDate:'2026-10-05',assignmentSource:'outra fonte'}),'medico-teste',now)).rejects.toThrow('ALOCACAO_CONFLITANTE');w=await changeWorkspace(w,event,'medico-teste',now);expect(w.followups[0]?.source.exactText).toContain('sem comparação');expect(w.followups[0]?.kind).toBe('IMAGING');});
 it('não promove notas nem critérios sem confirmação explícita',async()=>{await expect(changeWorkspace(initialWorkspace(),command('note',{noteText:'teste',noteType:'Flash',noteSource:'manual'}),'m',now)).rejects.toThrow('REVISAO');let w=await setup();const version=w.studies[0]!.reviews.length;await expect(changeWorkspace(w,command('study-review'),'m',now)).rejects.toThrow('REVISAO');expect(w.studies[0]!.reviews).toHaveLength(version);});
 it('mantém anexos binários e complementares sem inventar extração',async()=>{let w=await setup();w=await changeWorkspace(w,command('study-import',{fileName:'anexo.pdf',mime:'application/pdf',binary:Buffer.from('PDF SINTETICO').toString('base64'),attachCurrent:'sim'}),'m',now);expect(w.studies).toHaveLength(1);expect(w.studies[0]?.attachments[0]?.source.kind).toBe('BINARY_REFERENCE');expect(w.studies[0]?.attachments[0]?.source.contentHash).toHaveLength(64);expect(w.studies[0]?.reviews).toHaveLength(1);});
});
